/**
 * Lesson Metadata Registry
 * Comprehensive SEO and LLMO metadata for all course lessons
 */

import type { LessonMetadata, Publisher, Author } from './lesson-metadata.types'

// Common site configuration
const SITE_URL = 'https://queryright.dev' // Update with your actual domain
const SITE_NAME = 'QueryRight - Master Databases using QueryRight'
const SITE_TAGLINE = 'Master Databases using QueryRight'
const SITE_LOGO = '/logo-full.png'

const DEFAULT_AUTHOR: Author = {
  name: 'QueryRight Team',
  url: `${SITE_URL}/about`,
  email: 'hello@queryright.dev',
}

const DEFAULT_PUBLISHER: Publisher = {
  name: 'QueryRight',
  url: SITE_URL,
  logo: SITE_LOGO,
}

// Common keywords for database learning platform
const COMMON_KEYWORDS = [
  'database learning platform',
  'db practice',
  'interactive database tutorial',
  'learn database online',
  'database education',
  'hands-on database practice',
  'database training',
  'online database course',
  'SQL tutorial',
  'MongoDB tutorial',
]

/**
 * Generate lesson metadata
 */
function createLessonMetadata(
  data: Omit<
    LessonMetadata,
    | 'author'
    | 'publisher'
    | 'ogImage'
    | 'twitterCard'
    | 'inLanguage'
    | 'isAccessibleForFree'
    | 'canonicalUrl'
    | 'breadcrumbs'
  >,
): LessonMetadata {
  return {
    ...data,
    author: DEFAULT_AUTHOR,
    publisher: DEFAULT_PUBLISHER,
    ogImage: SITE_LOGO,
    twitterCard: 'summary_large_image',
    inLanguage: 'en-US',
    isAccessibleForFree: true,
    canonicalUrl: `${SITE_URL}/learning/${data.courseType}/${data.slug}`,
    breadcrumbs: [
      { position: 1, name: 'Home', item: SITE_URL },
      {
        position: 2,
        name: data.courseType.toUpperCase(),
        item: `${SITE_URL}/learning/${data.courseType}`,
      },
      {
        position: 3,
        name: data.moduleTitle,
        item: `${SITE_URL}/learning/${data.courseType}/${data.slug}`,
      },
      {
        position: 4,
        name: data.title,
        item: `${SITE_URL}/learning/${data.courseType}/${data.slug}`,
      },
    ],
  }
}

/**
 * SQL Course Metadata Registry
 */
export const sqlLessonsMetadata: Record<string, LessonMetadata> = {
  'introduction-to-databases': createLessonMetadata({
    id: 'mod_1_1',
    slug: 'introduction-to-databases',
    title:
      'Introduction to Relational Database Management Systems (RDBMS) | SQL Tutorial',
    description:
      'Learn the fundamentals of relational databases, RDBMS architecture, ACID properties, and database design principles. Perfect for beginners starting their SQL journey.',
    excerpt:
      'Master the foundations of relational database management systems including tables, relationships, ACID properties, and real-world database applications.',
    keywords: [
      ...COMMON_KEYWORDS,
      'RDBMS tutorial',
      'relational database basics',
      'database fundamentals',
      'SQL introduction',
      'database architecture',
      'ACID properties',
      'database tables',
      'learn SQL from scratch',
    ],
    category: 'SQL',
    difficulty: 'Beginner',
    estimatedReadingTime: 15,
    learningOutcomes: [
      'Understand what a database and RDBMS is',
      'Learn about tables, rows, and columns',
      'Master ACID properties and their importance',
      'Grasp the concept of primary and foreign keys',
      'Understand database relationships',
    ],
    prerequisites: [],
    courseType: 'sql',
    moduleId: 'module_1',
    moduleTitle: 'Module 1: SQL Foundations',
    ogType: 'article',
    datePublished: '2024-01-01T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Beginner',
    learningResourceType: 'LearningComponent',
    tags: [
      'RDBMS',
      'database basics',
      'SQL foundations',
      'database design',
      'relational model',
    ],
  }),

  'basic-select-queries': createLessonMetadata({
    id: 'mod_1_2',
    slug: 'basic-select-queries',
    title: 'Basic SELECT Queries in SQL - Complete Tutorial with Examples',
    description:
      'Master SQL SELECT statements with hands-on examples. Learn to retrieve data from databases, use wildcards, select specific columns, and write your first SQL queries.',
    excerpt:
      'Learn how to write basic SELECT queries to retrieve data from relational databases with practical examples and best practices.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL SELECT tutorial',
      'SELECT statement examples',
      'SQL query basics',
      'retrieve database data',
      'SQL wildcards',
      'database queries',
      'learn SQL SELECT',
    ],
    category: 'SQL',
    difficulty: 'Beginner',
    estimatedReadingTime: 12,
    learningOutcomes: [
      'Write basic SELECT statements',
      'Select specific columns from tables',
      'Use wildcards to select all columns',
      'Understand query execution order',
      'Format and structure SQL queries',
    ],
    prerequisites: ['introduction-to-databases'],
    courseType: 'sql',
    moduleId: 'module_1',
    moduleTitle: 'Module 1: SQL Foundations',
    ogType: 'article',
    datePublished: '2024-01-02T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Beginner',
    learningResourceType: 'LearningComponent',
    tags: ['SELECT statement', 'SQL queries', 'data retrieval', 'SQL basics'],
  }),

  'filtering-with-where': createLessonMetadata({
    id: 'mod_1_3',
    slug: 'filtering-with-where',
    title: 'SQL WHERE Clause Tutorial - Filter Data with Conditions',
    description:
      'Learn SQL WHERE clause to filter database records. Master comparison operators, logical operators (AND, OR, NOT), BETWEEN, IN, LIKE, and NULL handling in SQL queries.',
    excerpt:
      'Master data filtering in SQL using WHERE clause with comparison operators, logical conditions, pattern matching, and range queries.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL WHERE clause',
      'filter SQL data',
      'SQL conditions',
      'SQL operators',
      'AND OR NOT SQL',
      'SQL BETWEEN',
      'SQL IN operator',
      'SQL LIKE pattern matching',
    ],
    category: 'SQL',
    difficulty: 'Beginner',
    estimatedReadingTime: 14,
    learningOutcomes: [
      'Filter data using WHERE clause',
      'Use comparison operators (=, !=, <, >, <=, >=)',
      'Combine conditions with AND, OR, NOT',
      'Use BETWEEN for range queries',
      'Filter with IN operator',
      'Pattern matching with LIKE',
    ],
    prerequisites: ['basic-select-queries'],
    courseType: 'sql',
    moduleId: 'module_1',
    moduleTitle: 'Module 1: SQL Foundations',
    ogType: 'article',
    datePublished: '2024-01-03T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Beginner',
    learningResourceType: 'LearningComponent',
    tags: [
      'WHERE clause',
      'SQL filtering',
      'conditions',
      'operators',
      'data filtering',
    ],
  }),

  'sorting-and-limiting': createLessonMetadata({
    id: 'mod_1_4',
    slug: 'sorting-and-limiting',
    title: 'SQL ORDER BY and LIMIT - Sort and Limit Query Results',
    description:
      'Learn to sort SQL query results with ORDER BY (ASC, DESC) and limit results with LIMIT clause. Master data sorting, pagination, and result set control in databases.',
    excerpt:
      'Sort database query results in ascending or descending order and control the number of returned rows with ORDER BY and LIMIT clauses.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL ORDER BY',
      'SQL sort results',
      'SQL LIMIT',
      'SQL pagination',
      'ASC DESC SQL',
      'sort database data',
      'limit query results',
    ],
    category: 'SQL',
    difficulty: 'Beginner',
    estimatedReadingTime: 10,
    learningOutcomes: [
      'Sort query results with ORDER BY',
      'Use ascending (ASC) and descending (DESC) order',
      'Limit number of results with LIMIT',
      'Combine sorting with filtering',
      'Implement basic pagination',
    ],
    prerequisites: ['filtering-with-where'],
    courseType: 'sql',
    moduleId: 'module_1',
    moduleTitle: 'Module 1: SQL Foundations',
    ogType: 'article',
    datePublished: '2024-01-04T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Beginner',
    learningResourceType: 'LearningComponent',
    tags: ['ORDER BY', 'LIMIT', 'sorting', 'pagination', 'result control'],
  }),

  'aggregate-functions': createLessonMetadata({
    id: 'mod_1_5',
    slug: 'aggregate-functions',
    title: 'SQL Aggregate Functions - COUNT, SUM, AVG, MIN, MAX Tutorial',
    description:
      'Master SQL aggregate functions including COUNT, SUM, AVG, MIN, and MAX. Learn to calculate statistics, perform data analysis, and summarize database information.',
    excerpt:
      'Learn how to use SQL aggregate functions to calculate counts, sums, averages, minimums, and maximums for data analysis and reporting.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL aggregate functions',
      'COUNT function SQL',
      'SUM SQL',
      'AVG function',
      'MIN MAX SQL',
      'SQL data analysis',
      'database statistics',
      'SQL calculations',
    ],
    category: 'SQL',
    difficulty: 'Beginner',
    estimatedReadingTime: 13,
    learningOutcomes: [
      'Use COUNT to count rows',
      'Calculate totals with SUM',
      'Find averages with AVG',
      'Get minimum values with MIN',
      'Get maximum values with MAX',
      'Understand NULL handling in aggregates',
    ],
    prerequisites: ['sorting-and-limiting'],
    courseType: 'sql',
    moduleId: 'module_1',
    moduleTitle: 'Module 1: SQL Foundations',
    ogType: 'article',
    datePublished: '2024-01-05T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Beginner',
    learningResourceType: 'LearningComponent',
    tags: [
      'aggregate functions',
      'COUNT',
      'SUM',
      'AVG',
      'MIN',
      'MAX',
      'data analysis',
    ],
  }),

  'group-by-and-having': createLessonMetadata({
    id: 'mod_1_6',
    slug: 'group-by-and-having',
    title: 'SQL GROUP BY and HAVING Clause - Complete Tutorial with Examples',
    description:
      'Learn SQL GROUP BY to group data and HAVING clause to filter grouped results. Master data aggregation, grouping by multiple columns, and advanced filtering techniques.',
    excerpt:
      'Group database records and filter aggregated data using GROUP BY and HAVING clauses for powerful data analysis and reporting.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL GROUP BY',
      'SQL HAVING clause',
      'group data SQL',
      'filter grouped data',
      'SQL data grouping',
      'aggregate with GROUP BY',
      'HAVING vs WHERE',
    ],
    category: 'SQL',
    difficulty: 'Beginner',
    estimatedReadingTime: 15,
    learningOutcomes: [
      'Group data with GROUP BY clause',
      'Use aggregates with grouped data',
      'Filter groups with HAVING clause',
      'Understand WHERE vs HAVING',
      'Group by multiple columns',
    ],
    prerequisites: ['aggregate-functions'],
    courseType: 'sql',
    moduleId: 'module_1',
    moduleTitle: 'Module 1: SQL Foundations',
    ogType: 'article',
    datePublished: '2024-01-06T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Beginner',
    learningResourceType: 'LearningComponent',
    tags: [
      'GROUP BY',
      'HAVING',
      'data grouping',
      'filtering aggregates',
      'SQL aggregation',
    ],
  }),

  // Module 2: Data Manipulation
  'insert-statements': createLessonMetadata({
    id: 'mod_2_1',
    slug: 'insert-statements',
    title: 'SQL INSERT Statement - Add Data to Database Tables',
    description:
      'Learn SQL INSERT statements to add new records to database tables. Master single row inserts, multiple row inserts, and inserting data from queries.',
    excerpt:
      'Add new data to your database tables using SQL INSERT statements with practical examples and best practices.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL INSERT',
      'add database records',
      'insert data SQL',
      'SQL INSERT INTO',
      'multiple row insert',
      'database data entry',
    ],
    category: 'SQL',
    difficulty: 'Beginner',
    estimatedReadingTime: 12,
    learningOutcomes: [
      'Insert single rows into tables',
      'Insert multiple rows at once',
      'Insert data from SELECT queries',
      'Handle default values',
      'Understand INSERT syntax and best practices',
    ],
    prerequisites: ['group-by-and-having'],
    courseType: 'sql',
    moduleId: 'module_2',
    moduleTitle: 'Module 2: Data Manipulation',
    ogType: 'article',
    datePublished: '2024-01-07T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Beginner',
    learningResourceType: 'LearningComponent',
    tags: ['INSERT', 'data manipulation', 'add data', 'DML'],
  }),

  'update-statements': createLessonMetadata({
    id: 'mod_2_2',
    slug: 'update-statements',
    title: 'SQL UPDATE Statement - Modify Database Records',
    description:
      'Master SQL UPDATE statements to modify existing database records. Learn conditional updates, update multiple columns, and data modification best practices.',
    excerpt:
      'Modify existing database records using SQL UPDATE statements with WHERE clauses and learn safe data modification techniques.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL UPDATE',
      'modify database records',
      'update data SQL',
      'change database values',
      'SQL data modification',
    ],
    category: 'SQL',
    difficulty: 'Beginner',
    estimatedReadingTime: 11,
    learningOutcomes: [
      'Update single and multiple columns',
      'Use WHERE clause to target specific rows',
      'Update based on calculations',
      'Understand UPDATE safety',
      'Avoid common UPDATE mistakes',
    ],
    prerequisites: ['insert-statements'],
    courseType: 'sql',
    moduleId: 'module_2',
    moduleTitle: 'Module 2: Data Manipulation',
    ogType: 'article',
    datePublished: '2024-01-08T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Beginner',
    learningResourceType: 'LearningComponent',
    tags: ['UPDATE', 'modify data', 'data manipulation', 'DML'],
  }),

  'delete-statements': createLessonMetadata({
    id: 'mod_2_3',
    slug: 'delete-statements',
    title: 'SQL DELETE Statement - Remove Database Records Safely',
    description:
      'Learn SQL DELETE statements to remove records from database tables. Master conditional deletion, truncate vs delete, and safe data removal practices.',
    excerpt:
      'Safely remove records from database tables using SQL DELETE statements with proper filtering and best practices.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL DELETE',
      'remove database records',
      'delete data SQL',
      'SQL TRUNCATE',
      'safe data deletion',
    ],
    category: 'SQL',
    difficulty: 'Beginner',
    estimatedReadingTime: 10,
    learningOutcomes: [
      'Delete specific rows with WHERE clause',
      'Understand DELETE vs TRUNCATE',
      'Implement safe deletion practices',
      'Handle referential integrity',
      'Avoid accidental data loss',
    ],
    prerequisites: ['update-statements'],
    courseType: 'sql',
    moduleId: 'module_2',
    moduleTitle: 'Module 2: Data Manipulation',
    ogType: 'article',
    datePublished: '2024-01-09T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Beginner',
    learningResourceType: 'LearningComponent',
    tags: ['DELETE', 'remove data', 'data manipulation', 'TRUNCATE', 'DML'],
  }),

  'case-expressions': createLessonMetadata({
    id: 'mod_2_4',
    slug: 'case-expressions',
    title: 'SQL CASE Expression - Conditional Logic in Queries',
    description:
      'Master SQL CASE expressions for conditional logic. Learn simple CASE, searched CASE, and how to implement if-then-else logic in SQL queries.',
    excerpt:
      'Implement conditional logic in SQL queries using CASE expressions for dynamic data transformation and complex business rules.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL CASE',
      'CASE WHEN SQL',
      'SQL conditional logic',
      'SQL if-then-else',
      'CASE expression tutorial',
    ],
    category: 'SQL',
    difficulty: 'Intermediate',
    estimatedReadingTime: 14,
    learningOutcomes: [
      'Write simple CASE expressions',
      'Use searched CASE for complex conditions',
      'Implement if-then-else logic',
      'Use CASE in SELECT, WHERE, ORDER BY',
      'Handle NULL values in CASE',
    ],
    prerequisites: ['delete-statements'],
    courseType: 'sql',
    moduleId: 'module_2',
    moduleTitle: 'Module 2: Data Manipulation',
    ogType: 'article',
    datePublished: '2024-01-10T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Intermediate',
    learningResourceType: 'LearningComponent',
    tags: ['CASE', 'conditional logic', 'CASE WHEN', 'SQL expressions'],
  }),

  'null-handling': createLessonMetadata({
    id: 'mod_2_5',
    slug: 'null-handling',
    title: 'SQL NULL Values - Complete Guide to NULL Handling',
    description:
      'Learn everything about NULL values in SQL. Master IS NULL, IS NOT NULL, COALESCE, NULLIF functions, and NULL handling in queries and aggregates.',
    excerpt:
      'Understand and effectively handle NULL values in SQL databases with IS NULL, COALESCE, NULLIF, and NULL-safe comparisons.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL NULL',
      'IS NULL SQL',
      'COALESCE function',
      'NULLIF SQL',
      'handle NULL values',
      'NULL comparison',
    ],
    category: 'SQL',
    difficulty: 'Intermediate',
    estimatedReadingTime: 13,
    learningOutcomes: [
      'Understand what NULL represents',
      'Use IS NULL and IS NOT NULL',
      'Handle NULLs with COALESCE',
      'Use NULLIF for conditional NULLs',
      'Understand NULL in aggregates',
      'Avoid NULL comparison pitfalls',
    ],
    prerequisites: ['case-expressions'],
    courseType: 'sql',
    moduleId: 'module_2',
    moduleTitle: 'Module 2: Data Manipulation',
    ogType: 'article',
    datePublished: '2024-01-11T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Intermediate',
    learningResourceType: 'LearningComponent',
    tags: ['NULL', 'NULL handling', 'COALESCE', 'NULLIF', 'IS NULL'],
  }),

  // Module 3: Data Aggregation
  'count-and-sum': createLessonMetadata({
    id: 'mod_3_1',
    slug: 'count-and-sum',
    title: 'SQL COUNT and SUM Functions - Calculate Totals and Counts',
    description:
      'Deep dive into SQL COUNT and SUM functions. Learn COUNT(*), COUNT(column), COUNT(DISTINCT), SUM calculations, and advanced aggregation techniques.',
    excerpt:
      'Master COUNT and SUM aggregate functions for counting rows, distinct values, and calculating totals in SQL databases.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL COUNT',
      'SQL SUM',
      'COUNT DISTINCT',
      'COUNT(*)',
      'calculate totals SQL',
      'count rows SQL',
    ],
    category: 'SQL',
    difficulty: 'Intermediate',
    estimatedReadingTime: 12,
    learningOutcomes: [
      'Use COUNT(*) to count all rows',
      'Count non-NULL values',
      'Count distinct values',
      'Calculate sums with SUM',
      'Combine COUNT and SUM with GROUP BY',
    ],
    prerequisites: ['null-handling'],
    courseType: 'sql',
    moduleId: 'module_3',
    moduleTitle: 'Module 3: Data Aggregation',
    ogType: 'article',
    datePublished: '2024-01-12T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Intermediate',
    learningResourceType: 'LearningComponent',
    tags: ['COUNT', 'SUM', 'aggregate functions', 'data analysis', 'totals'],
  }),

  'avg-min-max': createLessonMetadata({
    id: 'mod_3_2',
    slug: 'avg-min-max',
    title: 'SQL AVG, MIN, MAX Functions - Statistical Analysis',
    description:
      'Learn SQL AVG, MIN, and MAX aggregate functions for statistical analysis. Calculate averages, find minimum and maximum values, and analyze data distributions.',
    excerpt:
      'Calculate averages and find minimum and maximum values using SQL AVG, MIN, and MAX functions for comprehensive data analysis.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL AVG',
      'SQL MIN MAX',
      'calculate average SQL',
      'find minimum maximum',
      'SQL statistics',
      'data analysis SQL',
    ],
    category: 'SQL',
    difficulty: 'Intermediate',
    estimatedReadingTime: 11,
    learningOutcomes: [
      'Calculate averages with AVG',
      'Find minimum values with MIN',
      'Find maximum values with MAX',
      'Handle NULL in calculations',
      'Combine with GROUP BY for analysis',
    ],
    prerequisites: ['count-and-sum'],
    courseType: 'sql',
    moduleId: 'module_3',
    moduleTitle: 'Module 3: Data Aggregation',
    ogType: 'article',
    datePublished: '2024-01-13T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Intermediate',
    learningResourceType: 'LearningComponent',
    tags: ['AVG', 'MIN', 'MAX', 'statistics', 'aggregate functions'],
  }),

  'group-by-basics': createLessonMetadata({
    id: 'mod_3_3',
    slug: 'group-by-basics',
    title: 'SQL GROUP BY Fundamentals - Group and Aggregate Data',
    description:
      'Master SQL GROUP BY basics. Learn to group data by single and multiple columns, use with aggregate functions, and understand grouping concepts.',
    excerpt:
      'Group database records and perform aggregate calculations using SQL GROUP BY clause for powerful data summarization.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL GROUP BY tutorial',
      'group data SQL',
      'SQL grouping',
      'aggregate by group',
      'GROUP BY multiple columns',
    ],
    category: 'SQL',
    difficulty: 'Intermediate',
    estimatedReadingTime: 13,
    learningOutcomes: [
      'Group data by single column',
      'Group by multiple columns',
      'Use aggregates with groups',
      'Understand GROUP BY execution',
      'Avoid common GROUP BY errors',
    ],
    prerequisites: ['avg-min-max'],
    courseType: 'sql',
    moduleId: 'module_3',
    moduleTitle: 'Module 3: Data Aggregation',
    ogType: 'article',
    datePublished: '2024-01-14T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Intermediate',
    learningResourceType: 'LearningComponent',
    tags: ['GROUP BY', 'data grouping', 'aggregation', 'SQL fundamentals'],
  }),

  'having-clause': createLessonMetadata({
    id: 'mod_3_4',
    slug: 'having-clause',
    title: 'SQL HAVING Clause - Filter Grouped Results',
    description:
      'Learn SQL HAVING clause to filter grouped and aggregated data. Understand the difference between WHERE and HAVING, and master advanced filtering techniques.',
    excerpt:
      'Filter aggregated results using SQL HAVING clause and learn when to use WHERE vs HAVING in your queries.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL HAVING',
      'HAVING clause tutorial',
      'filter grouped data',
      'WHERE vs HAVING',
      'filter aggregates SQL',
    ],
    category: 'SQL',
    difficulty: 'Intermediate',
    estimatedReadingTime: 12,
    learningOutcomes: [
      'Filter groups with HAVING',
      'Understand WHERE vs HAVING',
      'Use multiple HAVING conditions',
      'Combine WHERE and HAVING',
      'Filter on aggregate results',
    ],
    prerequisites: ['group-by-basics'],
    courseType: 'sql',
    moduleId: 'module_3',
    moduleTitle: 'Module 3: Data Aggregation',
    ogType: 'article',
    datePublished: '2024-01-15T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Intermediate',
    learningResourceType: 'LearningComponent',
    tags: ['HAVING', 'filter groups', 'aggregate filtering', 'SQL clauses'],
  }),

  'string-functions': createLessonMetadata({
    id: 'mod_3_5',
    slug: 'string-functions',
    title: 'SQL String Functions - Text Manipulation and Formatting',
    description:
      'Master SQL string functions including CONCAT, SUBSTRING, LENGTH, UPPER, LOWER, TRIM, REPLACE, and more. Learn text manipulation and formatting techniques.',
    excerpt:
      'Manipulate and format text data using SQL string functions for data cleaning, transformation, and presentation.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL string functions',
      'CONCAT SQL',
      'SUBSTRING SQL',
      'text manipulation SQL',
      'SQL UPPER LOWER',
      'TRIM function SQL',
    ],
    category: 'SQL',
    difficulty: 'Intermediate',
    estimatedReadingTime: 15,
    learningOutcomes: [
      'Concatenate strings with CONCAT',
      'Extract substrings with SUBSTRING',
      'Change case with UPPER/LOWER',
      'Trim whitespace with TRIM',
      'Replace text with REPLACE',
      'Get string length with LENGTH',
    ],
    prerequisites: ['having-clause'],
    courseType: 'sql',
    moduleId: 'module_3',
    moduleTitle: 'Module 3: Data Aggregation',
    ogType: 'article',
    datePublished: '2024-01-16T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Intermediate',
    learningResourceType: 'LearningComponent',
    tags: [
      'string functions',
      'text manipulation',
      'CONCAT',
      'SUBSTRING',
      'data formatting',
    ],
  }),

  'date-functions': createLessonMetadata({
    id: 'mod_3_6',
    slug: 'date-functions',
    title: 'SQL Date and Time Functions - Complete Guide',
    description:
      'Learn SQL date and time functions including NOW(), DATE(), YEAR(), MONTH(), DAY(), DATE_ADD(), DATE_SUB(), DATEDIFF(), and date formatting.',
    excerpt:
      'Work with dates and times in SQL using date functions for date arithmetic, extraction, formatting, and time-based analysis.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL date functions',
      'SQL time functions',
      'DATE SQL',
      'DATEDIFF SQL',
      'date arithmetic SQL',
      'format dates SQL',
    ],
    category: 'SQL',
    difficulty: 'Intermediate',
    estimatedReadingTime: 14,
    learningOutcomes: [
      'Get current date and time',
      'Extract date parts (year, month, day)',
      'Perform date arithmetic',
      'Calculate date differences',
      'Format dates and times',
      'Handle time zones',
    ],
    prerequisites: ['string-functions'],
    courseType: 'sql',
    moduleId: 'module_3',
    moduleTitle: 'Module 3: Data Aggregation',
    ogType: 'article',
    datePublished: '2024-01-17T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Intermediate',
    learningResourceType: 'LearningComponent',
    tags: [
      'date functions',
      'time functions',
      'date arithmetic',
      'DATEDIFF',
      'temporal data',
    ],
  }),

  // Module 4: Joins and Subqueries
  'inner-join': createLessonMetadata({
    id: 'mod_4_1',
    slug: 'inner-join',
    title: 'SQL INNER JOIN - Combine Data from Multiple Tables',
    description:
      'Master SQL INNER JOIN to combine related data from multiple tables. Learn join syntax, matching conditions, and how to work with related data.',
    excerpt:
      'Combine data from multiple related tables using SQL INNER JOIN to retrieve matching records based on common columns.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL INNER JOIN',
      'SQL joins tutorial',
      'join tables SQL',
      'combine tables SQL',
      'SQL table relationships',
      'relational queries',
    ],
    category: 'SQL',
    difficulty: 'Intermediate',
    estimatedReadingTime: 16,
    learningOutcomes: [
      'Understand INNER JOIN concept',
      'Write INNER JOIN queries',
      'Join multiple tables',
      'Use table aliases',
      'Understand join conditions',
      'Avoid Cartesian products',
    ],
    prerequisites: ['date-functions'],
    courseType: 'sql',
    moduleId: 'module_4',
    moduleTitle: 'Module 4: Joins and Subqueries',
    ogType: 'article',
    datePublished: '2024-01-18T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Intermediate',
    learningResourceType: 'LearningComponent',
    tags: [
      'INNER JOIN',
      'joins',
      'table relationships',
      'combine data',
      'SQL joins',
    ],
  }),

  'left-and-right-join': createLessonMetadata({
    id: 'mod_4_2',
    slug: 'left-and-right-join',
    title: 'SQL LEFT JOIN and RIGHT JOIN - Outer Joins Explained',
    description:
      'Learn SQL LEFT JOIN and RIGHT JOIN (outer joins) to include unmatched records. Master outer join concepts, NULL handling, and find missing relationships.',
    excerpt:
      'Retrieve all records from one table plus matching records from another using SQL LEFT JOIN and RIGHT JOIN outer joins.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL LEFT JOIN',
      'SQL RIGHT JOIN',
      'outer joins SQL',
      'LEFT OUTER JOIN',
      'RIGHT OUTER JOIN',
      'SQL join types',
    ],
    category: 'SQL',
    difficulty: 'Intermediate',
    estimatedReadingTime: 15,
    learningOutcomes: [
      'Understand LEFT JOIN concept',
      'Understand RIGHT JOIN concept',
      'Handle NULLs in outer joins',
      'Find unmatched records',
      'Choose between LEFT and RIGHT JOIN',
    ],
    prerequisites: ['inner-join'],
    courseType: 'sql',
    moduleId: 'module_4',
    moduleTitle: 'Module 4: Joins and Subqueries',
    ogType: 'article',
    datePublished: '2024-01-19T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Intermediate',
    learningResourceType: 'LearningComponent',
    tags: [
      'LEFT JOIN',
      'RIGHT JOIN',
      'outer joins',
      'unmatched records',
      'SQL joins',
    ],
  }),

  'full-outer-join': createLessonMetadata({
    id: 'mod_4_3',
    slug: 'full-outer-join',
    title: 'SQL FULL OUTER JOIN - Complete Join Tutorial',
    description:
      'Master SQL FULL OUTER JOIN to get all records from both tables. Learn to find all matches and non-matches, handle NULLs, and perform complete data reconciliation.',
    excerpt:
      'Retrieve all records from both tables, including matches and non-matches, using SQL FULL OUTER JOIN.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL FULL OUTER JOIN',
      'FULL JOIN SQL',
      'SQL all records join',
      'complete outer join',
      'data reconciliation SQL',
    ],
    category: 'SQL',
    difficulty: 'Advanced',
    estimatedReadingTime: 13,
    learningOutcomes: [
      'Understand FULL OUTER JOIN',
      'Get all records from both tables',
      'Handle NULLs from both sides',
      'Perform data reconciliation',
      'Emulate FULL JOIN in MySQL',
    ],
    prerequisites: ['left-and-right-join'],
    courseType: 'sql',
    moduleId: 'module_4',
    moduleTitle: 'Module 4: Joins and Subqueries',
    ogType: 'article',
    datePublished: '2024-01-20T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: [
      'FULL OUTER JOIN',
      'FULL JOIN',
      'outer joins',
      'data reconciliation',
    ],
  }),

  'self-joins': createLessonMetadata({
    id: 'mod_4_4',
    slug: 'self-joins',
    title: 'SQL Self Join - Join Table to Itself',
    description:
      'Learn SQL self joins to compare rows within the same table. Master hierarchical data, find relationships within tables, and use table aliases effectively.',
    excerpt:
      'Join a table to itself using SQL self joins to compare rows, work with hierarchical data, and find internal relationships.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL self join',
      'self join tutorial',
      'hierarchical data SQL',
      'join table to itself',
      'SQL recursive queries',
    ],
    category: 'SQL',
    difficulty: 'Advanced',
    estimatedReadingTime: 14,
    learningOutcomes: [
      'Understand self join concept',
      'Join table to itself',
      'Work with hierarchical data',
      'Use table aliases effectively',
      'Compare rows within same table',
    ],
    prerequisites: ['full-outer-join'],
    courseType: 'sql',
    moduleId: 'module_4',
    moduleTitle: 'Module 4: Joins and Subqueries',
    ogType: 'article',
    datePublished: '2024-01-21T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['self join', 'hierarchical data', 'table aliases', 'advanced joins'],
  }),

  subqueries: createLessonMetadata({
    id: 'mod_4_5',
    slug: 'subqueries',
    title: 'SQL Subqueries - Nested Queries Complete Guide',
    description:
      'Master SQL subqueries (nested queries) in SELECT, FROM, WHERE clauses. Learn scalar subqueries, row subqueries, table subqueries, and advanced nesting techniques.',
    excerpt:
      'Write powerful nested SQL queries using subqueries in SELECT, FROM, and WHERE clauses for complex data retrieval.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL subqueries',
      'nested queries SQL',
      'SQL subquery tutorial',
      'WHERE subquery',
      'FROM subquery',
      'scalar subquery',
    ],
    category: 'SQL',
    difficulty: 'Advanced',
    estimatedReadingTime: 17,
    learningOutcomes: [
      'Write subqueries in WHERE clause',
      'Use subqueries in FROM clause',
      'Create scalar subqueries',
      'Use IN, EXISTS with subqueries',
      'Understand subquery types',
      'Optimize subquery performance',
    ],
    prerequisites: ['self-joins'],
    courseType: 'sql',
    moduleId: 'module_4',
    moduleTitle: 'Module 4: Joins and Subqueries',
    ogType: 'article',
    datePublished: '2024-01-22T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['subqueries', 'nested queries', 'complex queries', 'advanced SQL'],
  }),

  'correlated-subqueries': createLessonMetadata({
    id: 'mod_4_6',
    slug: 'correlated-subqueries',
    title: 'SQL Correlated Subqueries - Advanced Nested Query Techniques',
    description:
      'Master SQL correlated subqueries that reference outer query columns. Learn EXISTS, NOT EXISTS, and advanced correlation patterns for complex data analysis.',
    excerpt:
      'Write advanced correlated subqueries that depend on outer query values using EXISTS, NOT EXISTS, and correlation patterns.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL correlated subqueries',
      'correlated queries SQL',
      'EXISTS SQL',
      'NOT EXISTS',
      'dependent subqueries',
      'advanced subqueries',
    ],
    category: 'SQL',
    difficulty: 'Advanced',
    estimatedReadingTime: 16,
    learningOutcomes: [
      'Understand correlated subqueries',
      'Use EXISTS and NOT EXISTS',
      'Write dependent subqueries',
      'Optimize correlated queries',
      'Choose between joins and subqueries',
    ],
    prerequisites: ['subqueries'],
    courseType: 'sql',
    moduleId: 'module_4',
    moduleTitle: 'Module 4: Joins and Subqueries',
    ogType: 'article',
    datePublished: '2024-01-23T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: [
      'correlated subqueries',
      'EXISTS',
      'NOT EXISTS',
      'advanced SQL',
      'dependent queries',
    ],
  }),

  // Module 5: Advanced Techniques
  'common-table-expressions': createLessonMetadata({
    id: 'mod_5_1',
    slug: 'common-table-expressions',
    title: 'SQL Common Table Expressions (CTE) - WITH Clause Tutorial',
    description:
      'Master SQL CTEs (Common Table Expressions) using WITH clause. Learn to write readable queries, recursive CTEs, and simplify complex SQL statements.',
    excerpt:
      'Simplify complex SQL queries and improve readability using Common Table Expressions (CTEs) with the WITH clause.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL CTE',
      'Common Table Expressions',
      'WITH clause SQL',
      'recursive CTE',
      'SQL WITH',
      'readable queries',
    ],
    category: 'SQL',
    difficulty: 'Advanced',
    estimatedReadingTime: 18,
    learningOutcomes: [
      'Write CTEs with WITH clause',
      'Simplify complex queries',
      'Use multiple CTEs',
      'Write recursive CTEs',
      'Improve query readability',
      'Understand CTE scope',
    ],
    prerequisites: ['correlated-subqueries'],
    courseType: 'sql',
    moduleId: 'module_5',
    moduleTitle: 'Module 5: Advanced Techniques',
    ogType: 'article',
    datePublished: '2024-01-24T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: [
      'CTE',
      'WITH clause',
      'Common Table Expressions',
      'recursive CTE',
      'advanced SQL',
    ],
  }),

  'window-functions': createLessonMetadata({
    id: 'mod_5_2',
    slug: 'window-functions',
    title: 'SQL Window Functions - OVER, PARTITION BY, ORDER BY Tutorial',
    description:
      'Master SQL window functions with OVER clause, PARTITION BY, ORDER BY. Learn analytical functions for running totals, ranking, and advanced data analysis.',
    excerpt:
      'Perform advanced analytical operations using SQL window functions with OVER, PARTITION BY, and frame specifications.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL window functions',
      'OVER clause SQL',
      'PARTITION BY',
      'SQL analytical functions',
      'running totals SQL',
      'SQL OVER',
    ],
    category: 'SQL',
    difficulty: 'Advanced',
    estimatedReadingTime: 20,
    learningOutcomes: [
      'Understand window functions',
      'Use OVER clause',
      'Partition data with PARTITION BY',
      'Define window frames',
      'Calculate running totals',
      'Perform advanced analytics',
    ],
    prerequisites: ['common-table-expressions'],
    courseType: 'sql',
    moduleId: 'module_5',
    moduleTitle: 'Module 5: Advanced Techniques',
    ogType: 'article',
    datePublished: '2024-01-25T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: [
      'window functions',
      'OVER',
      'PARTITION BY',
      'analytical functions',
      'advanced SQL',
    ],
  }),

  'rank-and-dense-rank': createLessonMetadata({
    id: 'mod_5_3',
    slug: 'rank-and-dense-rank',
    title: 'SQL RANK and DENSE_RANK - Ranking Window Functions',
    description:
      'Learn SQL RANK() and DENSE_RANK() window functions to assign rankings. Master ranking with ties, understand rank gaps, and implement leaderboards.',
    excerpt:
      'Assign rankings to rows using SQL RANK() and DENSE_RANK() window functions with proper handling of ties and gaps.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL RANK',
      'SQL DENSE_RANK',
      'ranking functions SQL',
      'SQL leaderboard',
      'rank with ties',
      'SQL rankings',
    ],
    category: 'SQL',
    difficulty: 'Advanced',
    estimatedReadingTime: 14,
    learningOutcomes: [
      'Use RANK() function',
      'Use DENSE_RANK() function',
      'Understand ranking differences',
      'Handle ties in rankings',
      'Implement leaderboards',
      'Partition rankings',
    ],
    prerequisites: ['window-functions'],
    courseType: 'sql',
    moduleId: 'module_5',
    moduleTitle: 'Module 5: Advanced Techniques',
    ogType: 'article',
    datePublished: '2024-01-26T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['RANK', 'DENSE_RANK', 'ranking', 'window functions', 'leaderboards'],
  }),

  'row-number': createLessonMetadata({
    id: 'mod_5_4',
    slug: 'row-number',
    title: 'SQL ROW_NUMBER - Unique Row Numbering Window Function',
    description:
      'Master SQL ROW_NUMBER() window function to assign unique sequential numbers to rows. Learn pagination, deduplication, and row identification techniques.',
    excerpt:
      'Assign unique sequential numbers to rows using SQL ROW_NUMBER() window function for pagination and deduplication.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL ROW_NUMBER',
      'ROW_NUMBER function',
      'SQL pagination',
      'deduplicate SQL',
      'unique row numbers',
      'SQL numbering',
    ],
    category: 'SQL',
    difficulty: 'Advanced',
    estimatedReadingTime: 13,
    learningOutcomes: [
      'Use ROW_NUMBER() function',
      'Implement pagination',
      'Deduplicate data',
      'Assign sequential numbers',
      'Partition row numbering',
    ],
    prerequisites: ['rank-and-dense-rank'],
    courseType: 'sql',
    moduleId: 'module_5',
    moduleTitle: 'Module 5: Advanced Techniques',
    ogType: 'article',
    datePublished: '2024-01-27T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: [
      'ROW_NUMBER',
      'pagination',
      'deduplication',
      'window functions',
      'row numbering',
    ],
  }),

  'lag-and-lead': createLessonMetadata({
    id: 'mod_5_5',
    slug: 'lag-and-lead',
    title: 'SQL LAG and LEAD - Access Previous and Next Row Data',
    description:
      'Learn SQL LAG() and LEAD() window functions to access data from previous and next rows. Master offset access for trend analysis and comparisons.',
    excerpt:
      'Access previous and next row values using SQL LAG() and LEAD() window functions for time-series analysis and comparisons.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL LAG',
      'SQL LEAD',
      'previous row SQL',
      'next row SQL',
      'time series SQL',
      'trend analysis SQL',
    ],
    category: 'SQL',
    difficulty: 'Advanced',
    estimatedReadingTime: 15,
    learningOutcomes: [
      'Use LAG() to access previous rows',
      'Use LEAD() to access next rows',
      'Compare current with previous values',
      'Analyze trends over time',
      'Handle NULL values in LAG/LEAD',
    ],
    prerequisites: ['row-number'],
    courseType: 'sql',
    moduleId: 'module_5',
    moduleTitle: 'Module 5: Advanced Techniques',
    ogType: 'article',
    datePublished: '2024-01-28T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['LAG', 'LEAD', 'window functions', 'time series', 'trend analysis'],
  }),

  'first-value-last-value': createLessonMetadata({
    id: 'mod_5_6',
    slug: 'first-value-last-value',
    title: 'SQL FIRST_VALUE and LAST_VALUE - Window Frame Functions',
    description:
      'Master SQL FIRST_VALUE() and LAST_VALUE() window functions to get first and last values in partitions. Learn frame specifications and boundary handling.',
    excerpt:
      'Retrieve first and last values from window frames using SQL FIRST_VALUE() and LAST_VALUE() functions with proper frame specifications.',
    keywords: [
      ...COMMON_KEYWORDS,
      'SQL FIRST_VALUE',
      'SQL LAST_VALUE',
      'window frames SQL',
      'first last values SQL',
      'frame specifications',
    ],
    category: 'SQL',
    difficulty: 'Advanced',
    estimatedReadingTime: 14,
    learningOutcomes: [
      'Use FIRST_VALUE() function',
      'Use LAST_VALUE() function',
      'Understand window frames',
      'Define frame boundaries',
      'Compare with first/last values',
    ],
    prerequisites: ['lag-and-lead'],
    courseType: 'sql',
    moduleId: 'module_5',
    moduleTitle: 'Module 5: Advanced Techniques',
    ogType: 'article',
    datePublished: '2024-01-29T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: [
      'FIRST_VALUE',
      'LAST_VALUE',
      'window functions',
      'window frames',
      'advanced SQL',
    ],
  }),

  // Add remaining modules following the same pattern...
  // Module 6 & 7 would continue with similar structure
}

/**
 * MongoDB Aggregation Pipeline Lessons Metadata
 */
const mongodbLessonsMetadata: Record<string, LessonMetadata> = {
  // Module 1: Aggregation Pipeline Basics
  'what-are-aggregation-pipelines': createLessonMetadata({
    id: 'mod_1_1',
    slug: 'what-are-aggregation-pipelines',
    title: 'What are MongoDB Aggregation Pipelines - Complete Guide',
    description:
      'Learn MongoDB aggregation pipelines from scratch. Understand how to process documents through stages, transform data, and perform complex data analysis in MongoDB.',
    excerpt:
      'Master MongoDB aggregation pipelines - the powerful framework for processing and transforming documents through multiple stages.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB aggregation',
      'aggregation pipeline',
      'MongoDB data processing',
      'document transformation',
      'MongoDB stages',
    ],
    category: 'MongoDB',
    difficulty: 'Beginner',
    estimatedReadingTime: 10,
    learningOutcomes: [
      'Understand aggregation pipeline concept',
      'Learn pipeline stages workflow',
      'Compare aggregation vs find queries',
      'Use basic aggregation syntax',
      'Process documents through stages',
    ],
    prerequisites: [],
    courseType: 'mongodb',
    moduleId: 'module_1',
    moduleTitle: 'Module 1: Aggregation Pipeline Basics',
    ogType: 'article',
    datePublished: '2024-02-01T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Beginner',
    learningResourceType: 'LearningComponent',
    tags: ['aggregation', 'pipeline', 'MongoDB basics', 'data processing'],
  }),

  'aggregation-framework-architecture': createLessonMetadata({
    id: 'mod_1_2',
    slug: 'aggregation-framework-architecture',
    title: 'MongoDB Aggregation Framework Architecture - Internal Design',
    description:
      'Dive deep into MongoDB aggregation framework architecture. Learn how stages execute, memory management, pipeline optimization, and internal processing.',
    excerpt:
      'Understand the internal architecture of MongoDB aggregation framework and how it efficiently processes data through pipeline stages.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB architecture',
      'aggregation framework',
      'pipeline optimization',
      'MongoDB internals',
      'stage execution',
    ],
    category: 'MongoDB',
    difficulty: 'Beginner',
    estimatedReadingTime: 12,
    learningOutcomes: [
      'Understand framework architecture',
      'Learn stage execution order',
      'Know memory management basics',
      'Understand pipeline optimization',
      'Learn query planning process',
    ],
    prerequisites: ['what-are-aggregation-pipelines'],
    courseType: 'mongodb',
    moduleId: 'module_1',
    moduleTitle: 'Module 1: Aggregation Pipeline Basics',
    ogType: 'article',
    datePublished: '2024-02-02T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Beginner',
    learningResourceType: 'LearningComponent',
    tags: ['architecture', 'framework', 'optimization', 'internals'],
  }),

  'match-stage': createLessonMetadata({
    id: 'mod_1_3',
    slug: 'match-stage',
    title: 'MongoDB $match Stage - Filter Documents in Aggregation',
    description:
      'Master MongoDB $match stage to filter documents in aggregation pipelines. Learn query operators, indexing, and performance optimization techniques.',
    excerpt:
      'Filter documents efficiently using MongoDB $match stage with query operators, comparison expressions, and index optimization.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB $match',
      '$match stage',
      'filter documents MongoDB',
      'aggregation filtering',
      'query operators',
    ],
    category: 'MongoDB',
    difficulty: 'Beginner',
    estimatedReadingTime: 11,
    learningOutcomes: [
      'Use $match stage effectively',
      'Apply query operators in pipelines',
      'Filter documents with conditions',
      'Optimize $match for performance',
      'Position $match early in pipeline',
    ],
    prerequisites: ['aggregation-framework-architecture'],
    courseType: 'mongodb',
    moduleId: 'module_1',
    moduleTitle: 'Module 1: Aggregation Pipeline Basics',
    ogType: 'article',
    datePublished: '2024-02-03T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Beginner',
    learningResourceType: 'LearningComponent',
    tags: ['$match', 'filtering', 'query operators', 'performance'],
  }),

  'project-stage': createLessonMetadata({
    id: 'mod_1_4',
    slug: 'project-stage',
    title: 'MongoDB $project Stage - Shape Documents and Transform Fields',
    description:
      'Learn MongoDB $project stage to reshape documents, include/exclude fields, compute new fields, and transform data in aggregation pipelines.',
    excerpt:
      'Transform and reshape MongoDB documents using $project stage with field inclusion, exclusion, renaming, and computed fields.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB $project',
      '$project stage',
      'reshape documents',
      'field transformation',
      'computed fields MongoDB',
    ],
    category: 'MongoDB',
    difficulty: 'Beginner',
    estimatedReadingTime: 13,
    learningOutcomes: [
      'Use $project to reshape documents',
      'Include and exclude fields',
      'Rename and compute new fields',
      'Use expressions in $project',
      'Transform nested documents',
    ],
    prerequisites: ['match-stage'],
    courseType: 'mongodb',
    moduleId: 'module_1',
    moduleTitle: 'Module 1: Aggregation Pipeline Basics',
    ogType: 'article',
    datePublished: '2024-02-04T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Beginner',
    learningResourceType: 'LearningComponent',
    tags: [
      '$project',
      'transformation',
      'field manipulation',
      'computed fields',
    ],
  }),

  'filtering-and-projection-lab': createLessonMetadata({
    id: 'mod_1_5',
    slug: 'filtering-and-projection-lab',
    title: 'MongoDB Filtering and Projection Lab - Hands-on Practice',
    description:
      'Practice MongoDB $match and $project stages with hands-on exercises. Build real-world aggregation pipelines combining filtering and projection.',
    excerpt:
      'Apply your knowledge of $match and $project stages through practical exercises and real-world scenarios.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB lab',
      'aggregation practice',
      'hands-on MongoDB',
      'pipeline exercises',
      'MongoDB tutorial',
    ],
    category: 'MongoDB',
    difficulty: 'Beginner',
    estimatedReadingTime: 15,
    learningOutcomes: [
      'Build complete aggregation pipelines',
      'Combine $match and $project stages',
      'Solve real-world data problems',
      'Debug pipeline errors',
      'Optimize pipeline performance',
    ],
    prerequisites: ['project-stage'],
    courseType: 'mongodb',
    moduleId: 'module_1',
    moduleTitle: 'Module 1: Aggregation Pipeline Basics',
    ogType: 'article',
    datePublished: '2024-02-05T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Beginner',
    learningResourceType: 'LearningComponent',
    tags: ['lab', 'practice', 'exercises', 'hands-on'],
  }),

  // Module 2: Grouping and Accumulation
  'group-stage': createLessonMetadata({
    id: 'mod_2_1',
    slug: 'group-stage',
    title: 'MongoDB $group Stage - Group Documents and Aggregate Data',
    description:
      'Master MongoDB $group stage to aggregate documents, calculate statistics, and group data by fields. Learn accumulator operators and grouping patterns.',
    excerpt:
      'Group and aggregate MongoDB documents using $group stage with accumulator operators for powerful data analysis.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB $group',
      '$group stage',
      'group documents MongoDB',
      'data aggregation',
      'accumulator operators',
    ],
    category: 'MongoDB',
    difficulty: 'Intermediate',
    estimatedReadingTime: 14,
    learningOutcomes: [
      'Group documents by fields',
      'Use _id for grouping keys',
      'Apply accumulator operators',
      'Calculate group statistics',
      'Handle multiple grouping levels',
    ],
    prerequisites: ['filtering-and-projection-lab'],
    courseType: 'mongodb',
    moduleId: 'module_2',
    moduleTitle: 'Module 2: Grouping and Accumulation',
    ogType: 'article',
    datePublished: '2024-02-06T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Intermediate',
    learningResourceType: 'LearningComponent',
    tags: ['$group', 'aggregation', 'grouping', 'statistics'],
  }),

  'accumulator-operators': createLessonMetadata({
    id: 'mod_2_2',
    slug: 'accumulator-operators',
    title: 'MongoDB Accumulator Operators - $sum, $avg, $min, $max, $push',
    description:
      'Learn MongoDB accumulator operators for aggregation: $sum, $avg, $min, $max, $push, $addToSet, $first, $last. Calculate statistics and accumulate values.',
    excerpt:
      'Master MongoDB accumulator operators to calculate sums, averages, min/max values, and build arrays in aggregation pipelines.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB accumulators',
      '$sum MongoDB',
      '$avg MongoDB',
      'accumulator operators',
      'aggregate statistics',
    ],
    category: 'MongoDB',
    difficulty: 'Intermediate',
    estimatedReadingTime: 16,
    learningOutcomes: [
      'Use $sum for totals',
      'Calculate averages with $avg',
      'Find min/max values',
      'Build arrays with $push',
      'Create unique sets with $addToSet',
    ],
    prerequisites: ['group-stage'],
    courseType: 'mongodb',
    moduleId: 'module_2',
    moduleTitle: 'Module 2: Grouping and Accumulation',
    ogType: 'article',
    datePublished: '2024-02-07T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Intermediate',
    learningResourceType: 'LearningComponent',
    tags: ['accumulators', '$sum', '$avg', '$push', 'statistics'],
  }),

  'unwind-stage': createLessonMetadata({
    id: 'mod_2_3',
    slug: 'unwind-stage',
    title: 'MongoDB $unwind Stage - Deconstruct Arrays in Aggregation',
    description:
      'Master MongoDB $unwind stage to deconstruct array fields into separate documents. Learn array handling, preserveNullAndEmptyArrays, and includeArrayIndex options.',
    excerpt:
      'Deconstruct MongoDB array fields into individual documents using $unwind stage for powerful array processing.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB $unwind',
      '$unwind stage',
      'array deconstruction',
      'flatten arrays MongoDB',
      'array processing',
    ],
    category: 'MongoDB',
    difficulty: 'Intermediate',
    estimatedReadingTime: 12,
    learningOutcomes: [
      'Deconstruct arrays with $unwind',
      'Handle null and empty arrays',
      'Include array indexes',
      'Process nested arrays',
      'Combine $unwind with $group',
    ],
    prerequisites: ['accumulator-operators'],
    courseType: 'mongodb',
    moduleId: 'module_2',
    moduleTitle: 'Module 2: Grouping and Accumulation',
    ogType: 'article',
    datePublished: '2024-02-08T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Intermediate',
    learningResourceType: 'LearningComponent',
    tags: ['$unwind', 'arrays', 'deconstruction', 'array processing'],
  }),

  'sort-and-limit-stages': createLessonMetadata({
    id: 'mod_2_4',
    slug: 'sort-and-limit-stages',
    title: 'MongoDB $sort and $limit Stages - Order and Limit Results',
    description:
      'Learn MongoDB $sort and $limit stages to order aggregation results and control output size. Understand sorting performance, memory limits, and best practices.',
    excerpt:
      'Order and limit MongoDB aggregation results using $sort and $limit stages with performance optimization techniques.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB $sort',
      'MongoDB $limit',
      'sort documents',
      'limit results MongoDB',
      'ordering aggregation',
    ],
    category: 'MongoDB',
    difficulty: 'Intermediate',
    estimatedReadingTime: 10,
    learningOutcomes: [
      'Sort documents in pipelines',
      'Use ascending and descending order',
      'Limit result set size',
      'Combine $sort with $limit',
      'Optimize sorting performance',
    ],
    prerequisites: ['unwind-stage'],
    courseType: 'mongodb',
    moduleId: 'module_2',
    moduleTitle: 'Module 2: Grouping and Accumulation',
    ogType: 'article',
    datePublished: '2024-02-09T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Intermediate',
    learningResourceType: 'LearningComponent',
    tags: ['$sort', '$limit', 'ordering', 'pagination'],
  }),

  'aggregation-analysis-lab': createLessonMetadata({
    id: 'mod_2_5',
    slug: 'aggregation-analysis-lab',
    title: 'MongoDB Aggregation Analysis Lab - Data Analytics Practice',
    description:
      'Practice MongoDB aggregation with hands-on data analytics exercises. Build complex pipelines using $group, $unwind, $sort, and accumulator operators.',
    excerpt:
      'Apply grouping, accumulation, and sorting concepts through practical data analytics scenarios and exercises.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB analytics',
      'data analysis MongoDB',
      'aggregation lab',
      'hands-on practice',
      'data analytics',
    ],
    category: 'MongoDB',
    difficulty: 'Intermediate',
    estimatedReadingTime: 18,
    learningOutcomes: [
      'Build analytics pipelines',
      'Calculate business metrics',
      'Process array data',
      'Generate reports with aggregation',
      'Optimize pipeline performance',
    ],
    prerequisites: ['sort-and-limit-stages'],
    courseType: 'mongodb',
    moduleId: 'module_2',
    moduleTitle: 'Module 2: Grouping and Accumulation',
    ogType: 'article',
    datePublished: '2024-02-10T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Intermediate',
    learningResourceType: 'LearningComponent',
    tags: ['lab', 'analytics', 'practice', 'data analysis'],
  }),

  // Module 3: Advanced Aggregation
  'lookup-stage': createLessonMetadata({
    id: 'mod_3_1',
    slug: 'lookup-stage',
    title: 'MongoDB $lookup Stage - Join Collections in Aggregation',
    description:
      'Master MongoDB $lookup stage for joining collections in aggregation pipelines. Learn left outer joins, uncorrelated and correlated subqueries.',
    excerpt:
      'Join MongoDB collections using $lookup stage to perform left outer joins and combine data from multiple collections.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB $lookup',
      'join collections MongoDB',
      '$lookup stage',
      'MongoDB joins',
      'collection relationships',
    ],
    category: 'MongoDB',
    difficulty: 'Advanced',
    estimatedReadingTime: 16,
    learningOutcomes: [
      'Join collections with $lookup',
      'Perform left outer joins',
      'Use pipeline syntax in $lookup',
      'Handle uncorrelated subqueries',
      'Implement correlated subqueries',
    ],
    prerequisites: ['aggregation-analysis-lab'],
    courseType: 'mongodb',
    moduleId: 'module_3',
    moduleTitle: 'Module 3: Advanced Aggregation',
    ogType: 'article',
    datePublished: '2024-02-11T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['$lookup', 'joins', 'relationships', 'subqueries'],
  }),

  'array-operations': createLessonMetadata({
    id: 'mod_3_2',
    slug: 'array-operations',
    title: 'MongoDB Array Operations - $filter, $map, $reduce in Aggregation',
    description:
      'Learn MongoDB array operators: $filter, $map, $reduce, $size, $slice, $arrayElemAt. Transform and manipulate arrays in aggregation pipelines.',
    excerpt:
      'Master MongoDB array operations to filter, transform, and process array fields in aggregation pipelines.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB arrays',
      '$filter MongoDB',
      '$map MongoDB',
      'array operators',
      'array manipulation',
    ],
    category: 'MongoDB',
    difficulty: 'Advanced',
    estimatedReadingTime: 17,
    learningOutcomes: [
      'Filter arrays with $filter',
      'Transform arrays with $map',
      'Reduce arrays with $reduce',
      'Access array elements',
      'Calculate array sizes',
    ],
    prerequisites: ['lookup-stage'],
    courseType: 'mongodb',
    moduleId: 'module_3',
    moduleTitle: 'Module 3: Advanced Aggregation',
    ogType: 'article',
    datePublished: '2024-02-12T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['arrays', '$filter', '$map', '$reduce', 'array operators'],
  }),

  'conditional-expressions': createLessonMetadata({
    id: 'mod_3_3',
    slug: 'conditional-expressions',
    title: 'MongoDB Conditional Expressions - $cond, $ifNull, $switch',
    description:
      'Master MongoDB conditional operators: $cond, $ifNull, $switch, $case. Implement conditional logic and branching in aggregation pipelines.',
    excerpt:
      'Implement conditional logic in MongoDB aggregation using $cond, $ifNull, and $switch operators.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB $cond',
      '$ifNull MongoDB',
      '$switch MongoDB',
      'conditional logic',
      'if-else MongoDB',
    ],
    category: 'MongoDB',
    difficulty: 'Advanced',
    estimatedReadingTime: 13,
    learningOutcomes: [
      'Use $cond for if-else logic',
      'Handle null values with $ifNull',
      'Implement multi-way branching with $switch',
      'Nest conditional expressions',
      'Build complex conditional logic',
    ],
    prerequisites: ['array-operations'],
    courseType: 'mongodb',
    moduleId: 'module_3',
    moduleTitle: 'Module 3: Advanced Aggregation',
    ogType: 'article',
    datePublished: '2024-02-13T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['conditional', '$cond', '$switch', 'logic', 'branching'],
  }),

  'string-manipulation': createLessonMetadata({
    id: 'mod_3_4',
    slug: 'string-manipulation',
    title: 'MongoDB String Manipulation - $concat, $substr, $split, $regex',
    description:
      'Learn MongoDB string operators: $concat, $substr, $split, $toLower, $toUpper, $regexMatch. Manipulate and transform text in aggregation pipelines.',
    excerpt:
      'Transform and manipulate strings in MongoDB aggregation using concatenation, substring, split, and regex operations.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB strings',
      'string manipulation MongoDB',
      '$concat MongoDB',
      'text processing',
      'regex MongoDB',
    ],
    category: 'MongoDB',
    difficulty: 'Advanced',
    estimatedReadingTime: 14,
    learningOutcomes: [
      'Concatenate strings with $concat',
      'Extract substrings',
      'Split strings into arrays',
      'Change case with $toLower/$toUpper',
      'Use regex for pattern matching',
    ],
    prerequisites: ['conditional-expressions'],
    courseType: 'mongodb',
    moduleId: 'module_3',
    moduleTitle: 'Module 3: Advanced Aggregation',
    ogType: 'article',
    datePublished: '2024-02-14T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: [
      'strings',
      '$concat',
      'text processing',
      'regex',
      'string operators',
    ],
  }),

  'complex-pipelines-lab': createLessonMetadata({
    id: 'mod_3_5',
    slug: 'complex-pipelines-lab',
    title: 'MongoDB Complex Pipelines Lab - Advanced Practice',
    description:
      'Build complex MongoDB aggregation pipelines combining $lookup, array operations, conditionals, and string manipulation. Real-world advanced scenarios.',
    excerpt:
      'Master complex MongoDB aggregation pipelines through hands-on practice with joins, array operations, and advanced transformations.',
    keywords: [
      ...COMMON_KEYWORDS,
      'complex pipelines MongoDB',
      'advanced aggregation',
      'MongoDB lab',
      'pipeline practice',
      'advanced MongoDB',
    ],
    category: 'MongoDB',
    difficulty: 'Advanced',
    estimatedReadingTime: 20,
    learningOutcomes: [
      'Build multi-stage pipelines',
      'Combine multiple operations',
      'Solve complex data problems',
      'Optimize advanced pipelines',
      'Debug complex aggregations',
    ],
    prerequisites: ['string-manipulation'],
    courseType: 'mongodb',
    moduleId: 'module_3',
    moduleTitle: 'Module 3: Advanced Aggregation',
    ogType: 'article',
    datePublished: '2024-02-15T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['lab', 'complex pipelines', 'advanced', 'practice'],
  }),

  // Module 4: Date and Math Operations
  'date-operators': createLessonMetadata({
    id: 'mod_4_1',
    slug: 'date-operators',
    title: 'MongoDB Date Operators - $dateToString, $dateDiff, Date Functions',
    description:
      'Master MongoDB date operators: $dateToString, $dateDiff, $dateAdd, $year, $month, $dayOfWeek. Work with dates and times in aggregation pipelines.',
    excerpt:
      'Manipulate and format dates in MongoDB aggregation using date operators for time-based analysis and transformations.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB dates',
      'date operators MongoDB',
      '$dateToString',
      'date functions',
      'time series MongoDB',
    ],
    category: 'MongoDB',
    difficulty: 'Intermediate',
    estimatedReadingTime: 15,
    learningOutcomes: [
      'Format dates with $dateToString',
      'Calculate date differences',
      'Extract date parts',
      'Add/subtract date intervals',
      'Work with timezones',
    ],
    prerequisites: ['complex-pipelines-lab'],
    courseType: 'mongodb',
    moduleId: 'module_4',
    moduleTitle: 'Module 4: Date and Math Operations',
    ogType: 'article',
    datePublished: '2024-02-16T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Intermediate',
    learningResourceType: 'LearningComponent',
    tags: ['dates', 'date operators', 'time series', 'datetime'],
  }),

  'arithmetic-operators': createLessonMetadata({
    id: 'mod_4_2',
    slug: 'arithmetic-operators',
    title: 'MongoDB Arithmetic Operators - $add, $subtract, $multiply, $divide',
    description:
      'Learn MongoDB arithmetic operators: $add, $subtract, $multiply, $divide, $mod, $pow. Perform mathematical calculations in aggregation pipelines.',
    excerpt:
      'Perform mathematical calculations in MongoDB aggregation using arithmetic operators for data transformations.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB math',
      'arithmetic operators',
      'calculations MongoDB',
      'mathematical functions',
      'MongoDB expressions',
    ],
    category: 'MongoDB',
    difficulty: 'Intermediate',
    estimatedReadingTime: 11,
    learningOutcomes: [
      'Add and subtract numbers',
      'Multiply and divide values',
      'Calculate modulo and power',
      'Round numbers',
      'Perform complex calculations',
    ],
    prerequisites: ['date-operators'],
    courseType: 'mongodb',
    moduleId: 'module_4',
    moduleTitle: 'Module 4: Date and Math Operations',
    ogType: 'article',
    datePublished: '2024-02-17T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Intermediate',
    learningResourceType: 'LearningComponent',
    tags: ['arithmetic', 'math', 'calculations', 'mathematical operators'],
  }),

  'comparison-and-boolean-logic': createLessonMetadata({
    id: 'mod_4_3',
    slug: 'comparison-and-boolean-logic',
    title: 'MongoDB Comparison and Boolean Logic - $eq, $gt, $and, $or, $not',
    description:
      'Master MongoDB comparison operators ($eq, $gt, $lt, $gte, $lte) and boolean logic ($and, $or, $not) for conditional expressions in aggregation.',
    excerpt:
      'Use MongoDB comparison and boolean operators to build complex conditional logic in aggregation pipelines.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB comparison',
      'boolean logic MongoDB',
      '$and $or MongoDB',
      'comparison operators',
      'conditional MongoDB',
    ],
    category: 'MongoDB',
    difficulty: 'Intermediate',
    estimatedReadingTime: 12,
    learningOutcomes: [
      'Use comparison operators',
      'Combine conditions with $and/$or',
      'Negate conditions with $not',
      'Build complex boolean logic',
      'Compare different data types',
    ],
    prerequisites: ['arithmetic-operators'],
    courseType: 'mongodb',
    moduleId: 'module_4',
    moduleTitle: 'Module 4: Date and Math Operations',
    ogType: 'article',
    datePublished: '2024-02-18T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Intermediate',
    learningResourceType: 'LearningComponent',
    tags: ['comparison', 'boolean', 'logic', 'operators', 'conditional'],
  }),

  'type-conversion': createLessonMetadata({
    id: 'mod_4_4',
    slug: 'type-conversion',
    title: 'MongoDB Type Conversion - $convert, $toString, $toInt, $toDouble',
    description:
      'Learn MongoDB type conversion operators: $convert, $toString, $toInt, $toDouble, $toDate. Transform data types safely in aggregation pipelines.',
    excerpt:
      'Convert between data types in MongoDB aggregation using type conversion operators for flexible data transformations.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB type conversion',
      '$convert MongoDB',
      'data types MongoDB',
      'type casting',
      'toString MongoDB',
    ],
    category: 'MongoDB',
    difficulty: 'Intermediate',
    estimatedReadingTime: 13,
    learningOutcomes: [
      'Convert strings to numbers',
      'Convert numbers to strings',
      'Convert to dates',
      'Handle conversion errors',
      'Use $convert with onError/onNull',
    ],
    prerequisites: ['comparison-and-boolean-logic'],
    courseType: 'mongodb',
    moduleId: 'module_4',
    moduleTitle: 'Module 4: Date and Math Operations',
    ogType: 'article',
    datePublished: '2024-02-19T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Intermediate',
    learningResourceType: 'LearningComponent',
    tags: ['type conversion', 'data types', 'casting', '$convert'],
  }),

  'data-transformation-lab': createLessonMetadata({
    id: 'mod_4_5',
    slug: 'data-transformation-lab',
    title: 'MongoDB Data Transformation Lab - Date, Math, and Type Operations',
    description:
      'Practice MongoDB data transformations with hands-on exercises using date operators, arithmetic operations, and type conversions in real scenarios.',
    excerpt:
      'Apply date, math, and type conversion operations through practical data transformation exercises.',
    keywords: [
      ...COMMON_KEYWORDS,
      'data transformation MongoDB',
      'MongoDB lab',
      'data processing',
      'transformation practice',
      'MongoDB exercises',
    ],
    category: 'MongoDB',
    difficulty: 'Intermediate',
    estimatedReadingTime: 17,
    learningOutcomes: [
      'Transform complex data',
      'Process dates and times',
      'Perform calculations',
      'Convert data types',
      'Build transformation pipelines',
    ],
    prerequisites: ['type-conversion'],
    courseType: 'mongodb',
    moduleId: 'module_4',
    moduleTitle: 'Module 4: Date and Math Operations',
    ogType: 'article',
    datePublished: '2024-02-20T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Intermediate',
    learningResourceType: 'LearningComponent',
    tags: ['lab', 'transformation', 'practice', 'data processing'],
  }),

  // Module 5: Pipeline Optimization
  'index-utilization': createLessonMetadata({
    id: 'mod_5_1',
    slug: 'index-utilization',
    title:
      'MongoDB Index Utilization in Aggregation - Performance Optimization',
    description:
      'Learn how MongoDB aggregation pipelines use indexes. Optimize pipeline performance with index selection, covered queries, and index intersection.',
    excerpt:
      'Optimize MongoDB aggregation performance by understanding index utilization and designing pipelines for efficient execution.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB indexes',
      'index utilization',
      'aggregation performance',
      'query optimization',
      'covered queries',
    ],
    category: 'MongoDB',
    difficulty: 'Advanced',
    estimatedReadingTime: 16,
    learningOutcomes: [
      'Understand index usage in pipelines',
      'Position stages for index utilization',
      'Create indexes for aggregations',
      'Use covered queries',
      'Analyze index selection',
    ],
    prerequisites: ['data-transformation-lab'],
    courseType: 'mongodb',
    moduleId: 'module_5',
    moduleTitle: 'Module 5: Pipeline Optimization',
    ogType: 'article',
    datePublished: '2024-02-21T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['indexes', 'optimization', 'performance', 'query planning'],
  }),

  'pipeline-performance': createLessonMetadata({
    id: 'mod_5_2',
    slug: 'pipeline-performance',
    title: 'MongoDB Pipeline Performance - Optimization Strategies',
    description:
      'Master MongoDB aggregation pipeline performance optimization. Learn stage ordering, memory management, allowDiskUse, and performance best practices.',
    excerpt:
      'Optimize MongoDB aggregation pipeline performance with strategic stage ordering, memory management, and best practices.',
    keywords: [
      ...COMMON_KEYWORDS,
      'pipeline performance',
      'MongoDB optimization',
      'aggregation tuning',
      'performance best practices',
      'allowDiskUse',
    ],
    category: 'MongoDB',
    difficulty: 'Advanced',
    estimatedReadingTime: 15,
    learningOutcomes: [
      'Optimize stage ordering',
      'Manage memory usage',
      'Use allowDiskUse option',
      'Apply performance best practices',
      'Identify bottlenecks',
    ],
    prerequisites: ['index-utilization'],
    courseType: 'mongodb',
    moduleId: 'module_5',
    moduleTitle: 'Module 5: Pipeline Optimization',
    ogType: 'article',
    datePublished: '2024-02-22T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['performance', 'optimization', 'tuning', 'best practices'],
  }),

  'explain-method': createLessonMetadata({
    id: 'mod_5_3',
    slug: 'explain-method',
    title: 'MongoDB explain() Method - Analyze Aggregation Performance',
    description:
      'Master MongoDB explain() method to analyze aggregation pipeline execution. Understand execution stats, query planning, and performance metrics.',
    excerpt:
      'Analyze and debug MongoDB aggregation pipeline performance using the explain() method and execution statistics.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB explain',
      'explain() method',
      'query analysis',
      'execution stats',
      'performance analysis',
    ],
    category: 'MongoDB',
    difficulty: 'Advanced',
    estimatedReadingTime: 14,
    learningOutcomes: [
      'Use explain() method',
      'Read execution statistics',
      'Analyze query plans',
      'Identify performance issues',
      'Understand execution stages',
    ],
    prerequisites: ['pipeline-performance'],
    courseType: 'mongodb',
    moduleId: 'module_5',
    moduleTitle: 'Module 5: Pipeline Optimization',
    ogType: 'article',
    datePublished: '2024-02-23T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['explain', 'analysis', 'performance', 'debugging'],
  }),

  'memory-management': createLessonMetadata({
    id: 'mod_5_4',
    slug: 'memory-management',
    title: 'MongoDB Aggregation Memory Management - Limits and Optimization',
    description:
      'Understand MongoDB aggregation memory limits, stage memory usage, and optimization strategies. Handle large datasets with allowDiskUse and streaming.',
    excerpt:
      'Manage MongoDB aggregation memory usage effectively with limits, allowDiskUse, and optimization techniques for large datasets.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB memory',
      'memory management',
      'memory limits',
      'allowDiskUse MongoDB',
      'large datasets',
    ],
    category: 'MongoDB',
    difficulty: 'Advanced',
    estimatedReadingTime: 13,
    learningOutcomes: [
      'Understand memory limits',
      'Monitor memory usage',
      'Use allowDiskUse effectively',
      'Optimize for large datasets',
      'Handle memory errors',
    ],
    prerequisites: ['explain-method'],
    courseType: 'mongodb',
    moduleId: 'module_5',
    moduleTitle: 'Module 5: Pipeline Optimization',
    ogType: 'article',
    datePublished: '2024-02-24T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['memory', 'optimization', 'allowDiskUse', 'large data'],
  }),

  'best-practices': createLessonMetadata({
    id: 'mod_5_5',
    slug: 'best-practices',
    title: 'MongoDB Aggregation Best Practices - Design and Optimization',
    description:
      'Learn MongoDB aggregation best practices for pipeline design, optimization, maintainability, and production deployment. Industry-proven patterns.',
    excerpt:
      'Apply MongoDB aggregation best practices for designing efficient, maintainable, and production-ready pipelines.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB best practices',
      'aggregation patterns',
      'pipeline design',
      'production MongoDB',
      'optimization patterns',
    ],
    category: 'MongoDB',
    difficulty: 'Advanced',
    estimatedReadingTime: 16,
    learningOutcomes: [
      'Follow best practices',
      'Design maintainable pipelines',
      'Apply optimization patterns',
      'Handle production scenarios',
      'Avoid common pitfalls',
    ],
    prerequisites: ['memory-management'],
    courseType: 'mongodb',
    moduleId: 'module_5',
    moduleTitle: 'Module 5: Pipeline Optimization',
    ogType: 'article',
    datePublished: '2024-02-25T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['best practices', 'patterns', 'design', 'production'],
  }),

  'optimization-lab': createLessonMetadata({
    id: 'mod_5_6',
    slug: 'optimization-lab',
    title: 'MongoDB Optimization Lab - Performance Tuning Practice',
    description:
      'Practice MongoDB aggregation optimization with hands-on exercises. Tune pipelines, analyze performance, use indexes, and apply best practices.',
    excerpt:
      'Master MongoDB aggregation optimization through practical exercises in performance tuning and pipeline analysis.',
    keywords: [
      ...COMMON_KEYWORDS,
      'optimization lab',
      'performance tuning MongoDB',
      'MongoDB practice',
      'pipeline optimization',
      'hands-on optimization',
    ],
    category: 'MongoDB',
    difficulty: 'Advanced',
    estimatedReadingTime: 20,
    learningOutcomes: [
      'Optimize real pipelines',
      'Analyze performance issues',
      'Apply tuning techniques',
      'Use explain() effectively',
      'Measure optimization impact',
    ],
    prerequisites: ['best-practices'],
    courseType: 'mongodb',
    moduleId: 'module_5',
    moduleTitle: 'Module 5: Pipeline Optimization',
    ogType: 'article',
    datePublished: '2024-02-26T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['lab', 'optimization', 'performance tuning', 'practice'],
  }),

  // Module 6: Real-World Applications
  'ecommerce-analytics': createLessonMetadata({
    id: 'mod_6_1',
    slug: 'ecommerce-analytics',
    title: 'MongoDB E-commerce Analytics - Sales and Customer Analysis',
    description:
      'Build MongoDB aggregation pipelines for e-commerce analytics: sales reports, customer segmentation, revenue analysis, and product performance.',
    excerpt:
      'Analyze e-commerce data with MongoDB aggregation: sales trends, customer behavior, and business metrics.',
    keywords: [
      ...COMMON_KEYWORDS,
      'e-commerce analytics',
      'sales analysis MongoDB',
      'customer analytics',
      'revenue reports',
      'MongoDB analytics',
    ],
    category: 'MongoDB',
    difficulty: 'Advanced',
    estimatedReadingTime: 18,
    learningOutcomes: [
      'Build sales reports',
      'Analyze customer behavior',
      'Calculate revenue metrics',
      'Segment customers',
      'Track product performance',
    ],
    prerequisites: ['optimization-lab'],
    courseType: 'mongodb',
    moduleId: 'module_6',
    moduleTitle: 'Module 6: Real-World Applications',
    ogType: 'article',
    datePublished: '2024-02-27T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['e-commerce', 'analytics', 'sales', 'customer analysis'],
  }),

  'time-series-analysis': createLessonMetadata({
    id: 'mod_6_2',
    slug: 'time-series-analysis',
    title: 'MongoDB Time-Series Analysis - Trends and Forecasting',
    description:
      'Perform time-series analysis with MongoDB aggregation: trend detection, moving averages, time-based grouping, and temporal patterns.',
    excerpt:
      'Analyze time-series data in MongoDB with aggregation pipelines for trends, patterns, and temporal analysis.',
    keywords: [
      ...COMMON_KEYWORDS,
      'time-series MongoDB',
      'time series analysis',
      'trend analysis',
      'temporal data',
      'moving averages',
    ],
    category: 'MongoDB',
    difficulty: 'Advanced',
    estimatedReadingTime: 17,
    learningOutcomes: [
      'Analyze time-series data',
      'Calculate moving averages',
      'Detect trends',
      'Group by time periods',
      'Handle temporal data',
    ],
    prerequisites: ['ecommerce-analytics'],
    courseType: 'mongodb',
    moduleId: 'module_6',
    moduleTitle: 'Module 6: Real-World Applications',
    ogType: 'article',
    datePublished: '2024-02-28T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['time-series', 'trends', 'temporal', 'analysis'],
  }),

  'geospatial-queries': createLessonMetadata({
    id: 'mod_6_3',
    slug: 'geospatial-queries',
    title: 'MongoDB Geospatial Queries - Location-Based Aggregation',
    description:
      'Master MongoDB geospatial aggregation: $geoNear, location-based queries, distance calculations, and spatial analysis in pipelines.',
    excerpt:
      'Perform geospatial analysis with MongoDB aggregation using $geoNear and location-based operators.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB geospatial',
      'location queries',
      '$geoNear MongoDB',
      'spatial analysis',
      'distance calculations',
    ],
    category: 'MongoDB',
    difficulty: 'Advanced',
    estimatedReadingTime: 16,
    learningOutcomes: [
      'Use $geoNear stage',
      'Query nearby locations',
      'Calculate distances',
      'Perform spatial analysis',
      'Index geospatial data',
    ],
    prerequisites: ['time-series-analysis'],
    courseType: 'mongodb',
    moduleId: 'module_6',
    moduleTitle: 'Module 6: Real-World Applications',
    ogType: 'article',
    datePublished: '2024-03-01T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['geospatial', 'location', '$geoNear', 'spatial'],
  }),

  'text-search-pipelines': createLessonMetadata({
    id: 'mod_6_4',
    slug: 'text-search-pipelines',
    title: 'MongoDB Text Search Pipelines - Full-Text Search Aggregation',
    description:
      'Implement MongoDB text search in aggregation pipelines: $text operator, text indexes, relevance scoring, and search result ranking.',
    excerpt:
      'Build full-text search capabilities in MongoDB aggregation with text indexes and relevance scoring.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB text search',
      'full-text search',
      '$text operator',
      'text indexes',
      'search ranking',
    ],
    category: 'MongoDB',
    difficulty: 'Advanced',
    estimatedReadingTime: 15,
    learningOutcomes: [
      'Implement text search',
      'Use $text operator',
      'Create text indexes',
      'Score search relevance',
      'Rank search results',
    ],
    prerequisites: ['geospatial-queries'],
    courseType: 'mongodb',
    moduleId: 'module_6',
    moduleTitle: 'Module 6: Real-World Applications',
    ogType: 'article',
    datePublished: '2024-03-02T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['text search', 'full-text', '$text', 'search'],
  }),

  'case-studies-lab': createLessonMetadata({
    id: 'mod_6_5',
    slug: 'case-studies-lab',
    title: 'MongoDB Real-World Case Studies Lab - Production Scenarios',
    description:
      'Solve real-world MongoDB aggregation challenges with hands-on case studies: analytics, reporting, and production scenarios.',
    excerpt:
      'Apply MongoDB aggregation skills to real-world case studies and production scenarios.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB case studies',
      'real-world MongoDB',
      'production scenarios',
      'business analytics',
      'MongoDB solutions',
    ],
    category: 'MongoDB',
    difficulty: 'Advanced',
    estimatedReadingTime: 22,
    learningOutcomes: [
      'Solve real-world problems',
      'Build production pipelines',
      'Handle business requirements',
      'Optimize for scale',
      'Apply best practices',
    ],
    prerequisites: ['text-search-pipelines'],
    courseType: 'mongodb',
    moduleId: 'module_6',
    moduleTitle: 'Module 6: Real-World Applications',
    ogType: 'article',
    datePublished: '2024-03-03T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['case studies', 'real-world', 'production', 'lab'],
  }),

  // Module 7: Advanced Techniques
  'facet-stage': createLessonMetadata({
    id: 'mod_7_1',
    slug: 'facet-stage',
    title: 'MongoDB $facet Stage - Multi-Faceted Aggregation',
    description:
      'Master MongoDB $facet stage to process multiple aggregation pipelines in parallel. Build faceted search, multi-dimensional analysis, and parallel processing.',
    excerpt:
      'Process multiple MongoDB aggregation pipelines simultaneously using $facet for parallel analysis and faceted search.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB $facet',
      'faceted search',
      'parallel aggregation',
      'multi-dimensional analysis',
      '$facet stage',
    ],
    category: 'MongoDB',
    difficulty: 'Advanced',
    estimatedReadingTime: 16,
    learningOutcomes: [
      'Use $facet for parallel pipelines',
      'Build faceted search',
      'Process multiple dimensions',
      'Combine facet results',
      'Optimize facet performance',
    ],
    prerequisites: ['case-studies-lab'],
    courseType: 'mongodb',
    moduleId: 'module_7',
    moduleTitle: 'Module 7: Advanced Techniques',
    ogType: 'article',
    datePublished: '2024-03-04T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['$facet', 'parallel', 'faceted search', 'multi-dimensional'],
  }),

  'bucket-stage': createLessonMetadata({
    id: 'mod_7_2',
    slug: 'bucket-stage',
    title: 'MongoDB $bucket Stage - Group Data into Ranges',
    description:
      'Learn MongoDB $bucket and $bucketAuto stages to categorize data into ranges. Create histograms, price ranges, and age groups in aggregation.',
    excerpt:
      'Categorize MongoDB data into buckets and ranges using $bucket and $bucketAuto for histograms and grouping.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB $bucket',
      '$bucketAuto',
      'data ranges',
      'histograms MongoDB',
      'categorization',
    ],
    category: 'MongoDB',
    difficulty: 'Advanced',
    estimatedReadingTime: 14,
    learningOutcomes: [
      'Use $bucket for ranges',
      'Automatically bucket with $bucketAuto',
      'Create histograms',
      'Categorize data',
      'Define custom boundaries',
    ],
    prerequisites: ['facet-stage'],
    courseType: 'mongodb',
    moduleId: 'module_7',
    moduleTitle: 'Module 7: Advanced Techniques',
    ogType: 'article',
    datePublished: '2024-03-05T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['$bucket', 'ranges', 'histograms', 'categorization'],
  }),

  'graph-lookup-stage': createLessonMetadata({
    id: 'mod_7_3',
    slug: 'graph-lookup-stage',
    title: 'MongoDB $graphLookup Stage - Recursive Relationships',
    description:
      'Master MongoDB $graphLookup for recursive queries and hierarchical data. Traverse graphs, organizational charts, social networks, and nested relationships.',
    excerpt:
      'Traverse MongoDB hierarchical and graph data structures recursively using $graphLookup stage.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB $graphLookup',
      'recursive queries',
      'hierarchical data',
      'graph traversal',
      'relationships MongoDB',
    ],
    category: 'MongoDB',
    difficulty: 'Advanced',
    estimatedReadingTime: 18,
    learningOutcomes: [
      'Use $graphLookup for recursion',
      'Traverse hierarchical data',
      'Query graph relationships',
      'Control recursion depth',
      'Build organizational charts',
    ],
    prerequisites: ['bucket-stage'],
    courseType: 'mongodb',
    moduleId: 'module_7',
    moduleTitle: 'Module 7: Advanced Techniques',
    ogType: 'article',
    datePublished: '2024-03-06T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['$graphLookup', 'recursive', 'hierarchical', 'graph'],
  }),

  'views-and-on-demand-pipelines': createLessonMetadata({
    id: 'mod_7_4',
    slug: 'views-and-on-demand-pipelines',
    title: 'MongoDB Views and On-Demand Pipelines - Reusable Aggregations',
    description:
      'Create MongoDB views for reusable aggregation pipelines. Build on-demand materialized views, simplify queries, and abstract complex aggregations.',
    excerpt:
      'Simplify MongoDB data access with views and reusable aggregation pipelines for clean abstraction and maintainability.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB views',
      'aggregation views',
      'materialized views',
      'on-demand pipelines',
      'reusable aggregations',
    ],
    category: 'MongoDB',
    difficulty: 'Advanced',
    estimatedReadingTime: 15,
    learningOutcomes: [
      'Create MongoDB views',
      'Build reusable pipelines',
      'Abstract complex aggregations',
      'Use views for security',
      'Optimize view performance',
    ],
    prerequisites: ['graph-lookup-stage'],
    courseType: 'mongodb',
    moduleId: 'module_7',
    moduleTitle: 'Module 7: Advanced Techniques',
    ogType: 'article',
    datePublished: '2024-03-07T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['views', 'reusability', 'abstraction', 'materialized views'],
  }),

  'final-project-dashboard': createLessonMetadata({
    id: 'mod_7_5',
    slug: 'final-project-dashboard',
    title: 'MongoDB Final Project - Build Analytics Dashboard',
    description:
      'Build a complete analytics dashboard using MongoDB aggregation. Combine all learned techniques: pipelines, optimization, real-world patterns.',
    excerpt:
      'Capstone project: Build a production-ready analytics dashboard combining all MongoDB aggregation techniques.',
    keywords: [
      ...COMMON_KEYWORDS,
      'MongoDB project',
      'analytics dashboard',
      'final project',
      'capstone MongoDB',
      'production dashboard',
    ],
    category: 'MongoDB',
    difficulty: 'Advanced',
    estimatedReadingTime: 25,
    learningOutcomes: [
      'Build complete analytics system',
      'Combine all aggregation techniques',
      'Create production-ready code',
      'Optimize for performance',
      'Deploy MongoDB solution',
    ],
    prerequisites: ['views-and-on-demand-pipelines'],
    courseType: 'mongodb',
    moduleId: 'module_7',
    moduleTitle: 'Module 7: Advanced Techniques',
    ogType: 'article',
    datePublished: '2024-03-08T00:00:00Z',
    dateModified: '2026-01-07T00:00:00Z',
    educationalLevel: 'Advanced',
    learningResourceType: 'LearningComponent',
    tags: ['final project', 'dashboard', 'capstone', 'production'],
  }),
}

// Helper function to get metadata by slug
export function getLessonMetadata(
  courseType: string,
  slug: string,
): LessonMetadata | null {
  if (courseType === 'sql') {
    return sqlLessonsMetadata[slug] || null
  }
  if (courseType === 'mongodb') {
    return mongodbLessonsMetadata[slug] || null
  }
  return null
}

// Helper function to get all metadata for a course
export function getAllLessonMetadata(courseType: string): LessonMetadata[] {
  if (courseType === 'sql') {
    return Object.values(sqlLessonsMetadata)
  }
  if (courseType === 'mongodb') {
    return Object.values(mongodbLessonsMetadata)
  }
  return []
}

export { SITE_URL, SITE_NAME, SITE_TAGLINE, SITE_LOGO }
