/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TypesGeneratorRouteImport } from './routes/types-generator'
import { Route as TestRouteImport } from './routes/test'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as QueryTyperRouteImport } from './routes/query-typer'
import { Route as QueryOptimizerRouteImport } from './routes/query-optimizer'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as MongoEditorRouteImport } from './routes/mongo-editor'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearningIndexRouteImport } from './routes/learning.index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as EditorQueryBuilderRouteImport } from './routes/$editor.query-builder'
import { Route as LearningCourseIndexRouteImport } from './routes/learning.$course.index'
import { Route as LearningCourseCourseIdRouteImport } from './routes/learning.$course.$courseId'

const TypesGeneratorRoute = TypesGeneratorRouteImport.update({
  id: '/types-generator',
  path: '/types-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryTyperRoute = QueryTyperRouteImport.update({
  id: '/query-typer',
  path: '/query-typer',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryOptimizerRoute = QueryOptimizerRouteImport.update({
  id: '/query-optimizer',
  path: '/query-optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const MongoEditorRoute = MongoEditorRouteImport.update({
  id: '/mongo-editor',
  path: '/mongo-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningIndexRoute = LearningIndexRouteImport.update({
  id: '/learning/',
  path: '/learning/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorQueryBuilderRoute = EditorQueryBuilderRouteImport.update({
  id: '/$editor/query-builder',
  path: '/$editor/query-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningCourseIndexRoute = LearningCourseIndexRouteImport.update({
  id: '/learning/$course/',
  path: '/learning/$course/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningCourseCourseIdRoute = LearningCourseCourseIdRouteImport.update({
  id: '/learning/$course/$courseId',
  path: '/learning/$course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/mongo-editor': typeof MongoEditorRoute
  '/practice': typeof PracticeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/query-optimizer': typeof QueryOptimizerRoute
  '/query-typer': typeof QueryTyperRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/test': typeof TestRoute
  '/types-generator': typeof TypesGeneratorRoute
  '/$editor/query-builder': typeof EditorQueryBuilderRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/learning': typeof LearningIndexRoute
  '/learning/$course/$courseId': typeof LearningCourseCourseIdRoute
  '/learning/$course': typeof LearningCourseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/mongo-editor': typeof MongoEditorRoute
  '/practice': typeof PracticeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/query-optimizer': typeof QueryOptimizerRoute
  '/query-typer': typeof QueryTyperRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/test': typeof TestRoute
  '/types-generator': typeof TypesGeneratorRoute
  '/$editor/query-builder': typeof EditorQueryBuilderRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/learning': typeof LearningIndexRoute
  '/learning/$course/$courseId': typeof LearningCourseCourseIdRoute
  '/learning/$course': typeof LearningCourseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/mongo-editor': typeof MongoEditorRoute
  '/practice': typeof PracticeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/query-optimizer': typeof QueryOptimizerRoute
  '/query-typer': typeof QueryTyperRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/test': typeof TestRoute
  '/types-generator': typeof TypesGeneratorRoute
  '/$editor/query-builder': typeof EditorQueryBuilderRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/learning/': typeof LearningIndexRoute
  '/learning/$course/$courseId': typeof LearningCourseCourseIdRoute
  '/learning/$course/': typeof LearningCourseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/editor'
    | '/mongo-editor'
    | '/practice'
    | '/privacy-policy'
    | '/query-optimizer'
    | '/query-typer'
    | '/terms-of-service'
    | '/test'
    | '/types-generator'
    | '/$editor/query-builder'
    | '/auth/login'
    | '/auth/signup'
    | '/learning'
    | '/learning/$course/$courseId'
    | '/learning/$course'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/editor'
    | '/mongo-editor'
    | '/practice'
    | '/privacy-policy'
    | '/query-optimizer'
    | '/query-typer'
    | '/terms-of-service'
    | '/test'
    | '/types-generator'
    | '/$editor/query-builder'
    | '/auth/login'
    | '/auth/signup'
    | '/learning'
    | '/learning/$course/$courseId'
    | '/learning/$course'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/editor'
    | '/mongo-editor'
    | '/practice'
    | '/privacy-policy'
    | '/query-optimizer'
    | '/query-typer'
    | '/terms-of-service'
    | '/test'
    | '/types-generator'
    | '/$editor/query-builder'
    | '/auth/login'
    | '/auth/signup'
    | '/learning/'
    | '/learning/$course/$courseId'
    | '/learning/$course/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EditorRoute: typeof EditorRoute
  MongoEditorRoute: typeof MongoEditorRoute
  PracticeRoute: typeof PracticeRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  QueryOptimizerRoute: typeof QueryOptimizerRoute
  QueryTyperRoute: typeof QueryTyperRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TestRoute: typeof TestRoute
  TypesGeneratorRoute: typeof TypesGeneratorRoute
  EditorQueryBuilderRoute: typeof EditorQueryBuilderRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  LearningIndexRoute: typeof LearningIndexRoute
  LearningCourseCourseIdRoute: typeof LearningCourseCourseIdRoute
  LearningCourseIndexRoute: typeof LearningCourseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/types-generator': {
      id: '/types-generator'
      path: '/types-generator'
      fullPath: '/types-generator'
      preLoaderRoute: typeof TypesGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query-typer': {
      id: '/query-typer'
      path: '/query-typer'
      fullPath: '/query-typer'
      preLoaderRoute: typeof QueryTyperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query-optimizer': {
      id: '/query-optimizer'
      path: '/query-optimizer'
      fullPath: '/query-optimizer'
      preLoaderRoute: typeof QueryOptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mongo-editor': {
      id: '/mongo-editor'
      path: '/mongo-editor'
      fullPath: '/mongo-editor'
      preLoaderRoute: typeof MongoEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/': {
      id: '/learning/'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$editor/query-builder': {
      id: '/$editor/query-builder'
      path: '/$editor/query-builder'
      fullPath: '/$editor/query-builder'
      preLoaderRoute: typeof EditorQueryBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/$course/': {
      id: '/learning/$course/'
      path: '/learning/$course'
      fullPath: '/learning/$course'
      preLoaderRoute: typeof LearningCourseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/$course/$courseId': {
      id: '/learning/$course/$courseId'
      path: '/learning/$course/$courseId'
      fullPath: '/learning/$course/$courseId'
      preLoaderRoute: typeof LearningCourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EditorRoute: EditorRoute,
  MongoEditorRoute: MongoEditorRoute,
  PracticeRoute: PracticeRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  QueryOptimizerRoute: QueryOptimizerRoute,
  QueryTyperRoute: QueryTyperRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TestRoute: TestRoute,
  TypesGeneratorRoute: TypesGeneratorRoute,
  EditorQueryBuilderRoute: EditorQueryBuilderRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  LearningIndexRoute: LearningIndexRoute,
  LearningCourseCourseIdRoute: LearningCourseCourseIdRoute,
  LearningCourseIndexRoute: LearningCourseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
