/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TypesGeneratorRouteImport } from './routes/types-generator'
import { Route as TestRouteImport } from './routes/test'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QueryTyperRouteImport } from './routes/query-typer'
import { Route as QueryOptimizerRouteImport } from './routes/query-optimizer'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as MongoEditorRouteImport } from './routes/mongo-editor'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearningIndexRouteImport } from './routes/learning.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as DashboardIdRouteImport } from './routes/dashboard.$id'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthMailsentRouteImport } from './routes/auth/mailsent'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiSitemapRouteImport } from './routes/api.sitemap'
import { Route as ApiCourseCatalogRouteImport } from './routes/api.course-catalog'
import { Route as EditorQueryBuilderRouteImport } from './routes/$editor.query-builder'
import { Route as LearningCourseIndexRouteImport } from './routes/learning.$course.index'
import { Route as LearningCourseCourseIdRouteImport } from './routes/learning.$course.$courseId'
import { Route as ApiLessonMetadataCourseSlugRouteImport } from './routes/api.lesson-metadata.$course.$slug'

const TypesGeneratorRoute = TypesGeneratorRouteImport.update({
  id: '/types-generator',
  path: '/types-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryTyperRoute = QueryTyperRouteImport.update({
  id: '/query-typer',
  path: '/query-typer',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryOptimizerRoute = QueryOptimizerRouteImport.update({
  id: '/query-optimizer',
  path: '/query-optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const MongoEditorRoute = MongoEditorRouteImport.update({
  id: '/mongo-editor',
  path: '/mongo-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningIndexRoute = LearningIndexRouteImport.update({
  id: '/learning/',
  path: '/learning/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIdRoute = DashboardIdRouteImport.update({
  id: '/dashboard/$id',
  path: '/dashboard/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMailsentRoute = AuthMailsentRouteImport.update({
  id: '/auth/mailsent',
  path: '/auth/mailsent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapRoute = ApiSitemapRouteImport.update({
  id: '/api/sitemap',
  path: '/api/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCourseCatalogRoute = ApiCourseCatalogRouteImport.update({
  id: '/api/course-catalog',
  path: '/api/course-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorQueryBuilderRoute = EditorQueryBuilderRouteImport.update({
  id: '/$editor/query-builder',
  path: '/$editor/query-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningCourseIndexRoute = LearningCourseIndexRouteImport.update({
  id: '/learning/$course/',
  path: '/learning/$course/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningCourseCourseIdRoute = LearningCourseCourseIdRouteImport.update({
  id: '/learning/$course/$courseId',
  path: '/learning/$course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLessonMetadataCourseSlugRoute =
  ApiLessonMetadataCourseSlugRouteImport.update({
    id: '/api/lesson-metadata/$course/$slug',
    path: '/api/lesson-metadata/$course/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/mongo-editor': typeof MongoEditorRoute
  '/practice': typeof PracticeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/query-optimizer': typeof QueryOptimizerRoute
  '/query-typer': typeof QueryTyperRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/test': typeof TestRoute
  '/types-generator': typeof TypesGeneratorRoute
  '/$editor/query-builder': typeof EditorQueryBuilderRoute
  '/api/course-catalog': typeof ApiCourseCatalogRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mailsent': typeof AuthMailsentRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/u/$username': typeof UUsernameRoute
  '/learning': typeof LearningIndexRoute
  '/learning/$course/$courseId': typeof LearningCourseCourseIdRoute
  '/learning/$course': typeof LearningCourseIndexRoute
  '/api/lesson-metadata/$course/$slug': typeof ApiLessonMetadataCourseSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/mongo-editor': typeof MongoEditorRoute
  '/practice': typeof PracticeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/query-optimizer': typeof QueryOptimizerRoute
  '/query-typer': typeof QueryTyperRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/test': typeof TestRoute
  '/types-generator': typeof TypesGeneratorRoute
  '/$editor/query-builder': typeof EditorQueryBuilderRoute
  '/api/course-catalog': typeof ApiCourseCatalogRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mailsent': typeof AuthMailsentRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/u/$username': typeof UUsernameRoute
  '/learning': typeof LearningIndexRoute
  '/learning/$course/$courseId': typeof LearningCourseCourseIdRoute
  '/learning/$course': typeof LearningCourseIndexRoute
  '/api/lesson-metadata/$course/$slug': typeof ApiLessonMetadataCourseSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/mongo-editor': typeof MongoEditorRoute
  '/practice': typeof PracticeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/query-optimizer': typeof QueryOptimizerRoute
  '/query-typer': typeof QueryTyperRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/test': typeof TestRoute
  '/types-generator': typeof TypesGeneratorRoute
  '/$editor/query-builder': typeof EditorQueryBuilderRoute
  '/api/course-catalog': typeof ApiCourseCatalogRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mailsent': typeof AuthMailsentRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/u/$username': typeof UUsernameRoute
  '/learning/': typeof LearningIndexRoute
  '/learning/$course/$courseId': typeof LearningCourseCourseIdRoute
  '/learning/$course/': typeof LearningCourseIndexRoute
  '/api/lesson-metadata/$course/$slug': typeof ApiLessonMetadataCourseSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editor'
    | '/mongo-editor'
    | '/practice'
    | '/privacy-policy'
    | '/query-optimizer'
    | '/query-typer'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/test'
    | '/types-generator'
    | '/$editor/query-builder'
    | '/api/course-catalog'
    | '/api/sitemap'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/mailsent'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify'
    | '/dashboard/$id'
    | '/u/$username'
    | '/learning'
    | '/learning/$course/$courseId'
    | '/learning/$course'
    | '/api/lesson-metadata/$course/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editor'
    | '/mongo-editor'
    | '/practice'
    | '/privacy-policy'
    | '/query-optimizer'
    | '/query-typer'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/test'
    | '/types-generator'
    | '/$editor/query-builder'
    | '/api/course-catalog'
    | '/api/sitemap'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/mailsent'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify'
    | '/dashboard/$id'
    | '/u/$username'
    | '/learning'
    | '/learning/$course/$courseId'
    | '/learning/$course'
    | '/api/lesson-metadata/$course/$slug'
  id:
    | '__root__'
    | '/'
    | '/editor'
    | '/mongo-editor'
    | '/practice'
    | '/privacy-policy'
    | '/query-optimizer'
    | '/query-typer'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/test'
    | '/types-generator'
    | '/$editor/query-builder'
    | '/api/course-catalog'
    | '/api/sitemap'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/mailsent'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify'
    | '/dashboard/$id'
    | '/u/$username'
    | '/learning/'
    | '/learning/$course/$courseId'
    | '/learning/$course/'
    | '/api/lesson-metadata/$course/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRoute: typeof EditorRoute
  MongoEditorRoute: typeof MongoEditorRoute
  PracticeRoute: typeof PracticeRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  QueryOptimizerRoute: typeof QueryOptimizerRoute
  QueryTyperRoute: typeof QueryTyperRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TestRoute: typeof TestRoute
  TypesGeneratorRoute: typeof TypesGeneratorRoute
  EditorQueryBuilderRoute: typeof EditorQueryBuilderRoute
  ApiCourseCatalogRoute: typeof ApiCourseCatalogRoute
  ApiSitemapRoute: typeof ApiSitemapRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMailsentRoute: typeof AuthMailsentRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  DashboardIdRoute: typeof DashboardIdRoute
  UUsernameRoute: typeof UUsernameRoute
  LearningIndexRoute: typeof LearningIndexRoute
  LearningCourseCourseIdRoute: typeof LearningCourseCourseIdRoute
  LearningCourseIndexRoute: typeof LearningCourseIndexRoute
  ApiLessonMetadataCourseSlugRoute: typeof ApiLessonMetadataCourseSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/types-generator': {
      id: '/types-generator'
      path: '/types-generator'
      fullPath: '/types-generator'
      preLoaderRoute: typeof TypesGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query-typer': {
      id: '/query-typer'
      path: '/query-typer'
      fullPath: '/query-typer'
      preLoaderRoute: typeof QueryTyperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query-optimizer': {
      id: '/query-optimizer'
      path: '/query-optimizer'
      fullPath: '/query-optimizer'
      preLoaderRoute: typeof QueryOptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mongo-editor': {
      id: '/mongo-editor'
      path: '/mongo-editor'
      fullPath: '/mongo-editor'
      preLoaderRoute: typeof MongoEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/': {
      id: '/learning/'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$id': {
      id: '/dashboard/$id'
      path: '/dashboard/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof DashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/mailsent': {
      id: '/auth/mailsent'
      path: '/auth/mailsent'
      fullPath: '/auth/mailsent'
      preLoaderRoute: typeof AuthMailsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap': {
      id: '/api/sitemap'
      path: '/api/sitemap'
      fullPath: '/api/sitemap'
      preLoaderRoute: typeof ApiSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/course-catalog': {
      id: '/api/course-catalog'
      path: '/api/course-catalog'
      fullPath: '/api/course-catalog'
      preLoaderRoute: typeof ApiCourseCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$editor/query-builder': {
      id: '/$editor/query-builder'
      path: '/$editor/query-builder'
      fullPath: '/$editor/query-builder'
      preLoaderRoute: typeof EditorQueryBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/$course/': {
      id: '/learning/$course/'
      path: '/learning/$course'
      fullPath: '/learning/$course'
      preLoaderRoute: typeof LearningCourseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/$course/$courseId': {
      id: '/learning/$course/$courseId'
      path: '/learning/$course/$courseId'
      fullPath: '/learning/$course/$courseId'
      preLoaderRoute: typeof LearningCourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lesson-metadata/$course/$slug': {
      id: '/api/lesson-metadata/$course/$slug'
      path: '/api/lesson-metadata/$course/$slug'
      fullPath: '/api/lesson-metadata/$course/$slug'
      preLoaderRoute: typeof ApiLessonMetadataCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRoute,
  MongoEditorRoute: MongoEditorRoute,
  PracticeRoute: PracticeRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  QueryOptimizerRoute: QueryOptimizerRoute,
  QueryTyperRoute: QueryTyperRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TestRoute: TestRoute,
  TypesGeneratorRoute: TypesGeneratorRoute,
  EditorQueryBuilderRoute: EditorQueryBuilderRoute,
  ApiCourseCatalogRoute: ApiCourseCatalogRoute,
  ApiSitemapRoute: ApiSitemapRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthMailsentRoute: AuthMailsentRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  DashboardIdRoute: DashboardIdRoute,
  UUsernameRoute: UUsernameRoute,
  LearningIndexRoute: LearningIndexRoute,
  LearningCourseCourseIdRoute: LearningCourseCourseIdRoute,
  LearningCourseIndexRoute: LearningCourseIndexRoute,
  ApiLessonMetadataCourseSlugRoute: ApiLessonMetadataCourseSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
