/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TypesGeneratorRouteImport } from './routes/types-generator'
import { Route as QueryTyperRouteImport } from './routes/query-typer'
import { Route as QueryOptimizerRouteImport } from './routes/query-optimizer'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearningIndexRouteImport } from './routes/learning.index'
import { Route as EditorQueryBuilderRouteImport } from './routes/$editor.query-builder'
import { Route as LearningCourseIndexRouteImport } from './routes/learning.$course.index'
import { Route as LearningCourseCourseIdRouteImport } from './routes/learning.$course.$courseId'

const TypesGeneratorRoute = TypesGeneratorRouteImport.update({
  id: '/types-generator',
  path: '/types-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryTyperRoute = QueryTyperRouteImport.update({
  id: '/query-typer',
  path: '/query-typer',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryOptimizerRoute = QueryOptimizerRouteImport.update({
  id: '/query-optimizer',
  path: '/query-optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningIndexRoute = LearningIndexRouteImport.update({
  id: '/learning/',
  path: '/learning/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorQueryBuilderRoute = EditorQueryBuilderRouteImport.update({
  id: '/$editor/query-builder',
  path: '/$editor/query-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningCourseIndexRoute = LearningCourseIndexRouteImport.update({
  id: '/learning/$course/',
  path: '/learning/$course/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningCourseCourseIdRoute = LearningCourseCourseIdRouteImport.update({
  id: '/learning/$course/$courseId',
  path: '/learning/$course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/query-optimizer': typeof QueryOptimizerRoute
  '/query-typer': typeof QueryTyperRoute
  '/types-generator': typeof TypesGeneratorRoute
  '/$editor/query-builder': typeof EditorQueryBuilderRoute
  '/learning': typeof LearningIndexRoute
  '/learning/$course/$courseId': typeof LearningCourseCourseIdRoute
  '/learning/$course': typeof LearningCourseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/query-optimizer': typeof QueryOptimizerRoute
  '/query-typer': typeof QueryTyperRoute
  '/types-generator': typeof TypesGeneratorRoute
  '/$editor/query-builder': typeof EditorQueryBuilderRoute
  '/learning': typeof LearningIndexRoute
  '/learning/$course/$courseId': typeof LearningCourseCourseIdRoute
  '/learning/$course': typeof LearningCourseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/query-optimizer': typeof QueryOptimizerRoute
  '/query-typer': typeof QueryTyperRoute
  '/types-generator': typeof TypesGeneratorRoute
  '/$editor/query-builder': typeof EditorQueryBuilderRoute
  '/learning/': typeof LearningIndexRoute
  '/learning/$course/$courseId': typeof LearningCourseCourseIdRoute
  '/learning/$course/': typeof LearningCourseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editor'
    | '/query-optimizer'
    | '/query-typer'
    | '/types-generator'
    | '/$editor/query-builder'
    | '/learning'
    | '/learning/$course/$courseId'
    | '/learning/$course'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editor'
    | '/query-optimizer'
    | '/query-typer'
    | '/types-generator'
    | '/$editor/query-builder'
    | '/learning'
    | '/learning/$course/$courseId'
    | '/learning/$course'
  id:
    | '__root__'
    | '/'
    | '/editor'
    | '/query-optimizer'
    | '/query-typer'
    | '/types-generator'
    | '/$editor/query-builder'
    | '/learning/'
    | '/learning/$course/$courseId'
    | '/learning/$course/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRoute: typeof EditorRoute
  QueryOptimizerRoute: typeof QueryOptimizerRoute
  QueryTyperRoute: typeof QueryTyperRoute
  TypesGeneratorRoute: typeof TypesGeneratorRoute
  EditorQueryBuilderRoute: typeof EditorQueryBuilderRoute
  LearningIndexRoute: typeof LearningIndexRoute
  LearningCourseCourseIdRoute: typeof LearningCourseCourseIdRoute
  LearningCourseIndexRoute: typeof LearningCourseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/types-generator': {
      id: '/types-generator'
      path: '/types-generator'
      fullPath: '/types-generator'
      preLoaderRoute: typeof TypesGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query-typer': {
      id: '/query-typer'
      path: '/query-typer'
      fullPath: '/query-typer'
      preLoaderRoute: typeof QueryTyperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query-optimizer': {
      id: '/query-optimizer'
      path: '/query-optimizer'
      fullPath: '/query-optimizer'
      preLoaderRoute: typeof QueryOptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/': {
      id: '/learning/'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$editor/query-builder': {
      id: '/$editor/query-builder'
      path: '/$editor/query-builder'
      fullPath: '/$editor/query-builder'
      preLoaderRoute: typeof EditorQueryBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/$course/': {
      id: '/learning/$course/'
      path: '/learning/$course'
      fullPath: '/learning/$course'
      preLoaderRoute: typeof LearningCourseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/$course/$courseId': {
      id: '/learning/$course/$courseId'
      path: '/learning/$course/$courseId'
      fullPath: '/learning/$course/$courseId'
      preLoaderRoute: typeof LearningCourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRoute,
  QueryOptimizerRoute: QueryOptimizerRoute,
  QueryTyperRoute: QueryTyperRoute,
  TypesGeneratorRoute: TypesGeneratorRoute,
  EditorQueryBuilderRoute: EditorQueryBuilderRoute,
  LearningIndexRoute: LearningIndexRoute,
  LearningCourseCourseIdRoute: LearningCourseCourseIdRoute,
  LearningCourseIndexRoute: LearningCourseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
