/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TypesGeneratorRouteImport } from './routes/types-generator'
import { Route as QueryTyperRouteImport } from './routes/query-typer'
import { Route as QueryBuilderRouteImport } from './routes/query-builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearningCourseCourseIdRouteImport } from './routes/learning.$course.$courseId'

const TypesGeneratorRoute = TypesGeneratorRouteImport.update({
  id: '/types-generator',
  path: '/types-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryTyperRoute = QueryTyperRouteImport.update({
  id: '/query-typer',
  path: '/query-typer',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryBuilderRoute = QueryBuilderRouteImport.update({
  id: '/query-builder',
  path: '/query-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningCourseCourseIdRoute = LearningCourseCourseIdRouteImport.update({
  id: '/learning/$course/$courseId',
  path: '/learning/$course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/query-builder': typeof QueryBuilderRoute
  '/query-typer': typeof QueryTyperRoute
  '/types-generator': typeof TypesGeneratorRoute
  '/learning/$course/$courseId': typeof LearningCourseCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/query-builder': typeof QueryBuilderRoute
  '/query-typer': typeof QueryTyperRoute
  '/types-generator': typeof TypesGeneratorRoute
  '/learning/$course/$courseId': typeof LearningCourseCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/query-builder': typeof QueryBuilderRoute
  '/query-typer': typeof QueryTyperRoute
  '/types-generator': typeof TypesGeneratorRoute
  '/learning/$course/$courseId': typeof LearningCourseCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/query-builder'
    | '/query-typer'
    | '/types-generator'
    | '/learning/$course/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/query-builder'
    | '/query-typer'
    | '/types-generator'
    | '/learning/$course/$courseId'
  id:
    | '__root__'
    | '/'
    | '/query-builder'
    | '/query-typer'
    | '/types-generator'
    | '/learning/$course/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QueryBuilderRoute: typeof QueryBuilderRoute
  QueryTyperRoute: typeof QueryTyperRoute
  TypesGeneratorRoute: typeof TypesGeneratorRoute
  LearningCourseCourseIdRoute: typeof LearningCourseCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/types-generator': {
      id: '/types-generator'
      path: '/types-generator'
      fullPath: '/types-generator'
      preLoaderRoute: typeof TypesGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query-typer': {
      id: '/query-typer'
      path: '/query-typer'
      fullPath: '/query-typer'
      preLoaderRoute: typeof QueryTyperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query-builder': {
      id: '/query-builder'
      path: '/query-builder'
      fullPath: '/query-builder'
      preLoaderRoute: typeof QueryBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/$course/$courseId': {
      id: '/learning/$course/$courseId'
      path: '/learning/$course/$courseId'
      fullPath: '/learning/$course/$courseId'
      preLoaderRoute: typeof LearningCourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QueryBuilderRoute: QueryBuilderRoute,
  QueryTyperRoute: QueryTyperRoute,
  TypesGeneratorRoute: TypesGeneratorRoute,
  LearningCourseCourseIdRoute: LearningCourseCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
